### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by CECHAMO81** [ShadowMario/FNF-PsychEngine#15841] opened 2024-11-02 01:42 UTC
### What feature do you want to get added on the **base** engine?

More than asking for a feature, I would like to add a Spanish translation for Latin America (I created my translation and if it doesn't end up in the official Psych Engine, I will distribute it as a mod or translation of the Psych Engine). I am willing to change the dialogues to Spanish and their correct interpretation (maybe I would add the Tankman voices in Spanish if possible).
I would like to help with other translations into French, but I am terrible at translating many technical things.
For those who want to try my idea, I will launch an unofficial translation of the compiled engine on itch.io (just interface translation and some dialogues).
[es-MX.txt](https://github.com/user-attachments/files/17605170/es-MX.txt)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CECHAMO81** [comment] 2024-11-04 02:51
I'm experimenting a bit with translations, and it might be a good idea to reduce the font sizes, as some translations take up more space than others
I really don't know if this can be done or not, in the end it's just a comment

**Comment by KELOTOMU** [comment] 2024-11-09 02:24
What about the main menu and story menu, drawn assets need to be translated

**Comment by CECHAMO81** [comment] 2024-11-09 04:24
> What about the main menu and story menu, drawn assets need to be translated

You can easily reuse the ones that are already made, although it is an example of a proposal, in any case if I need to I can also draw the precision ones.

**Comment by ShadowMario** [comment] 2024-11-11 04:16
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/15093

**Closed by ShadowMario** 2024-11-11 04:16 UTC
Labels: enhancement
