### ISSUE TITLE
Game Crashed when importing json

### ISSUE THREAD

**Issue by TabbyX** [ShadowMario/FNF-PsychEngine#11171] opened 2022-11-07 03:55 UTC
### Describe your bug here.

I was trying to make a rechart of expulsion, but when I imported it into my psych engine, the game crashed and gave me this crash error: 

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2957)
editors/ChartingState.hx (line 434)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/expulsion/expulsion.json]

I honestly have no idea what to do.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Didn't modify anything.

**Comment by frantastic24** [comment] 2022-11-07 04:35
Not a bug
Missing chart

**Comment by DisIsNOt** [comment] 2022-11-08 14:02
Now close this burj

**Closed** 2022-11-09 05:33 UTC
Labels: bug
