### ISSUE TITLE
Character not play animation

### ISSUE THREAD

**Issue by FujiwaraZachWatterson** [ShadowMario/FNF-PsychEngine#10003] opened 2022-08-01 07:48 UTC
### Describe your bug here.

The Character didn't want to play animation (On hiting note)

Opponent and Player

If don't know how here the Explain:

https://user-images.githubusercontent.com/109717730/182099387-86c99ab2-c8b6-4847-9c58-767a5bbd8a77.mp4

It's a Working Project btw

and it happen when change bpm

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I do not edit the build

**Comment by frantastic24** [comment] 2022-08-01 14:41
Not a bug
Section is alt animation, which the character doesn't have

**Comment by FujiwaraZachWatterson** [comment] 2022-08-02 05:58
welp i'm actually stupid

i'm already realize it's alt animation section

i'm risky myself

**Comment by frantastic24** [comment] 2022-08-02 06:15
Close the issue

**Closed** 2023-07-19 17:12 UTC
Labels: bug
