### ISSUE TITLE
Feature request: Soft-Coded settings

### ISSUE THREAD

**Issue by El-Neno** [ShadowMario/FNF-PsychEngine#11077] opened 2022-11-01 00:59 UTC
### My idea here is to make a mods folder called something like "settings".

Then, you can make .txt files that include the **setting**, the **description**, the **option menu** (like "gameplay" or "visuals and ui") a **variable name**,  a **default value** (this can help with making it a bool or an int) and finally **if it depends on another setting** (Something like making it uneditable if another option is deactivated).

After that, it could be accesible as a variable, for things like a custom botplay text

### example (YOU DONT NEED TO INCLUDE IT, ITS JUST AN EXAMPLE. ALSO DONT MAKE THE SYNTAX LIKE THIS):

setting name: Showcase mode
description: Enable a showcase mode, where it activates botplay, and it gives it a unique text!
menu: Modifiers
variable name: showcase
default value: false
depends: false

and then you could do something like this in a global script (one in mods/scripts)
if showcase == true then
      setProperty('botplayTxt.text', 'SHOWCASE MODE')
      setPropertyFromClass('ClientPrefs', 'cpucontrolled', true)
end

just an idea i had and i hope you liked it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment] 2022-11-01 01:12
Duplicate of several other issues

**Comment by El-Neno** [comment] 2022-11-01 01:56
> 

_wait what i didnt know_

**Comment by frantastic24** [comment] 2022-11-01 02:00
Also since Lua supports both save files and file reading this is already possible, but you're not getting a menu for it and I doubt there's any plans to change that

**Comment by CaptainBaldi** [comment] 2022-11-01 10:15
y'all mfs want soft coded everything istg

**Comment by MaybeMaru** [comment] 2022-11-01 16:15
you can already do this lol

**Closed** 2022-11-14 21:05 UTC
Labels: enhancement
