### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Bread-11** [ShadowMario/FNF-PsychEngine#10269] opened 2022-08-21 20:35 UTC
### Describe your bug here.

I get this error when trying to compile psych engine

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:593: lines 593-597 : Int should be Bool
source/FunkinLua.hx:593: lines 593-597 : For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment] 2022-08-21 20:51
Not a bug and a duplicate, look it up in issues

**Comment by Bread-11** [comment] 2022-08-21 20:56
> Not a bug and a duplicate, look it up in issues

I can't find it

**Comment by Bread-11** [comment] 2022-08-21 20:59
> Not a bug and a duplicate, look it up in issues

Thanks!

**Comment by CrusherNotDrip** [comment] 2022-08-21 21:00
If that helped your problem close the issue

**Comment by TheKitBoi** [comment] 2022-08-21 21:37
Close the issue
![B153684A-EE72-4951-A4BB-547642BB53D4](https://user-images.githubusercontent.com/84044666/185811955-51b7bcd4-cc61-4d40-9982-7cb9af993139.jpeg)

**Closed** 2023-07-19 17:18 UTC
Labels: bug
