### ISSUE TITLE
Costum week appears Double

### ISSUE THREAD

**Issue by DaGhostyDude** [ShadowMario/FNF-PsychEngine#1844] opened 2021-12-08 18:12 UTC
### Describe your problem here.

I´m building a psych engine mod by myself for the first time with source code. i mean, I download the source code and stuff. I'm trying to add my own week,
if I press 7 the debug mode doesn't come up, even if I enter the compiled version, so I'm adding the costume stuff by hand.

my problem is that my week appears double, but one just without the week icon.
my Week json I got from a working debug/building on another game so everything is correct.
when I port it to my uncompiled game, it just. as said doubles.

when I remove my week from the "weeks.txt" one seems to disappear, which is the one with the icon meaning its pretty impossible for me to finish this week, without either not having a week sprite or being doubled..

did this ever happen to anyone before? please help?

![bug](https://user-images.githubusercontent.com/86105531/145261164-915ca414-b1da-4aac-a9b6-b8a9732711f2.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope.

**Comment by ShadowMario** [comment] 2021-12-09 00:40
You have a duplicate of your week .json somewhere.
Check inside mods/weeks/, assets/preload/weeks/

**Closed by ShadowMario** 2021-12-09 00:40 UTC
Labels: help wanted

**Comment by DaGhostyDude** [comment] 2021-12-09 10:54
> You have a duplicate of your week .json somewhere. Check inside mods/weeks/, assets/preload/weeks/

after like 30-40 minutes of research i can confirm that there is no double json of my week...tho as said in the post it seems to have some kind of interaction with the "WeekList.txt" (when i add Week8 into it the week doubles with a sprite, when i remove it only the one without sprite stays)
