### ISSUE TITLE
Reloading the image in the Character Editor crashes Psych Engine.

### ISSUE THREAD

**Issue by mystic-akito** [ShadowMario/FNF-PsychEngine#485] opened 2021-10-19 23:25 UTC
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

Hello, whenever I try to reload the image in the character editor, it crashes the game. It seems like other people are having the same issue. I've tried everything, like: Deleting the assets and putting it back, looking at the xml file, etc. Nothing helps. What should I do?

**Comment by DevScyu** [comment] 2021-10-19 23:56
Duplicate of #483

**Closed** 2021-10-20 14:55 UTC
Labels: help wanted

**Comment by Hackx2** [comment] 2021-11-27 09:17
when i add a animation that is correct with the xml it says error
