### ISSUE TITLE
How do I add a loading screen to desktop builds?

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#1756] opened 2021-12-05 22:24 UTC
### Describe your problem here.

I tried messing with the Project.xml but nothing I tried worked. I can't find a way to add loading screens to the desktop versions of psych.

Does anyone know how to add the loading screens to desktop builds?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by kaysancoder** [comment] 2021-12-05 23:49
do you mean like entity mod thing? if yes well this the answer:

Just delete no_preload_all on loadingstate.hx
is easy tho
but unfortunately it will be useless, since load a song wont take so much time

also if you get any error of like this, delete #end line

ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected }
![error2](https://user-images.githubusercontent.com/89194591/144769036-95761a05-d23a-4fd9-95ca-3252aca8fa58.png)

ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected }
![error1](https://user-images.githubusercontent.com/89194591/144769057-86f5e295-6d7b-41db-9a6b-1a5f4a57b2b5.png)

And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)

I hope this usefull for you!

If you have any question, go dm me in discord! (Kaysan#3035)

**Comment by ShadowMario** [comment] 2021-12-06 01:10
Duplicate of [#1441 ](https://github.com/ShadowMario/FNF-PsychEngine/issues/1441)

**Closed by ShadowMario** 2021-12-06 01:10 UTC
Labels: help wanted
