### ISSUE TITLE
Bro the menu adding for a character dont work

### ISSUE THREAD

**Issue by FireGZM** [ShadowMario/FNF-PsychEngine#726] opened 2021-10-30 23:06 UTC
### Describe your bug here.

I make the spritesheet and da XML and it STILL crashes

### Are you modding a build from source or with Lua?

- [ ] Lua
- [X] Source

### What is your build target?

- [X] Windows
- [ ] Linux
- [ ] Mac
- [ ] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Credits.HX, TitleState.Hv

**Comment by MeowcaTheoRange** [comment] 2021-10-30 23:15
Duplicate of #723

**Closed** 2021-10-30 23:59 UTC
Labels: bug
