### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by SoulkingBG** [ShadowMario/FNF-PsychEngine#11910] opened 2023-02-13 19:54 UTC
### Describe your problem here.
so i just added a new stage and managed to put everything in place but when i decidet to put it in the song it was intendet to be it showed this

PlayState.hx (line 2469)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

How can i fix it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment] 2023-02-13 19:59
your custom note xml is broken

**Comment by SoulkingBG** [comment] 2023-02-13 20:02
I havent made any custom notes

**Comment by frantastic24** [comment] 2023-02-13 20:28
Duplicate of #10566

**Comment by SoulkingBG** [comment] 2023-02-13 20:31
Found my mistake thx

**Comment by TheKitBoi** [comment] 2023-02-13 20:36
close this issue

**Closed** 2023-02-14 04:46 UTC
Labels: help wanted
