### ISSUE TITLE
Lua shader

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10558] opened 2022-09-16 04:34 UTC
### Describe your problem here.

How can I add a .frag format shader to a stage using .lua, can someone tell me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment] 2022-09-16 06:32
Duplicate of #10251

**Comment by DisIsNOt** [comment] 2022-09-16 10:31
setSpriteShader() yes

**Comment by frantastic24** [comment] 2022-09-16 18:07
setCameraShader isn't a thing

**Comment by joxu13v** [comment] 2022-09-16 21:11
> setCameraShader isn't a thing 

but without that it doesn't work either

**Comment by frantastic24** [comment] 2022-09-16 22:06
Your object is wrong, the shader is wrong, shader doesn't exist or your version doesn't support shaders

**Closed** 2023-07-19 15:48 UTC
Labels: help wanted
