### ISSUE TITLE
im raging over this

### ISSUE THREAD

**Issue by DominusDary** [ShadowMario/FNF-PsychEngine#9715] opened 2022-07-15 18:44 UTC
### Describe your bug here.

![image](https://user-images.githubusercontent.com/109384179/179290530-615ce607-bdec-428b-b70e-88567027b159.png)
   

PLEASE HELP BRUH

### Command Prompt/Terminal logs (if existing)

```bash
wydm im new to github
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by DominusDary** [comment] 2022-07-15 18:44
FIX NOW

**Comment by frantastic24** [comment] 2022-07-15 20:08
duplicate of #9296

**Closed** 2022-07-20 14:22 UTC
Labels: bug
