### ISSUE TITLE
Why does my char even put error

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#2462] opened 2021-12-21 18:13 UTC
### Describe your problem here.

Why does my char says (ERROR!)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment] 2021-12-21 19:31
animation xml name is wrong

**Comment by juanroman74454811** [comment] 2021-12-22 03:55
Thanks bbpanzu, have a good day

**Comment by dum-du-m** [comment] 2021-12-22 07:25
> Thanks bbpanzu, have a good day

the issue is solved pls close the issue

**Closed** 2021-12-23 22:13 UTC
Labels: help wanted
