### ISSUE TITLE
Stage event

### ISSUE THREAD

**Issue by ComaYami** [ShadowMario/FNF-PsychEngine#2124] opened 2021-12-14 17:53 UTC
### What feature do you want to get added on the base engine?

a event that changes the stage during the song i think no one knows how to do that on psych engine yet so it would great to have it if not thats okay <3

**Comment by CrusherMods** [comment] 2021-12-14 18:35
Many people have asked for this, stop asking

**Comment by HiroMizuki** [comment] 2021-12-14 19:01
shadow mario said that he's not going to add it cuz he don't want to make coding more complicated

**Comment by bbpanzu** [comment] 2021-12-14 20:52
You could have another stage lua code and call it in another stage code with the addLuaScript function.

**Comment by ShadowMario** [comment] 2021-12-15 04:39
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/529, https://github.com/ShadowMario/FNF-PsychEngine/issues/1280, https://github.com/ShadowMario/FNF-PsychEngine/issues/1923, https://github.com/ShadowMario/FNF-PsychEngine/issues/2073

**Closed by ShadowMario** 2021-12-15 04:39 UTC
Labels: duplicate, enhancement, i swear to god
