### ISSUE TITLE
Engine don't compile

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#2067] opened 2021-12-13 15:42 UTC
### Describe your problem here.

I downloaded the engine this afternoon, added a few sprites and xml's and tried to compile but when i try to compile it gives me this error:
source/Song.hx:64: characters 27-41 : Array access is not allowed on {+ length : Int }

Pls help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i only added a few sprites

**Comment by CrusherMods** [comment] 2021-12-13 15:56
Try updating Haxe AND STOP MAKING DUPLICITES OMG

**Comment by ShadowMario** [comment] 2021-12-13 18:12
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/2049, https://github.com/ShadowMario/FNF-PsychEngine/issues/2038, https://github.com/ShadowMario/FNF-PsychEngine/issues/2028, https://github.com/ShadowMario/FNF-PsychEngine/issues/2027, https://github.com/ShadowMario/FNF-PsychEngine/issues/2026, https://github.com/ShadowMario/FNF-PsychEngine/issues/2024

Don't use the source code on Github's release, use the main repo.

**Closed by ShadowMario** 2021-12-13 18:12 UTC
Labels: help wanted

**Comment by RedMik52** [comment] 2021-12-14 21:00
sorry if it spammed idk why, i shutted down my PC after I send the issue.
