### ISSUE TITLE
The engine won't compile

### ISSUE THREAD

**Issue by SomeRandomGuyHere** [ShadowMario/FNF-PsychEngine#2053] opened 2021-12-13 03:56 UTC
### Describe your bug here.

When compiling with the new 0.5 update, the engine won't compile even if it was new.

### Command Prompt/Terminal logs (if existing)

```bash
source/StoryMenuState.hx:323: characters 12-14 : Expected )
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing at all, completely new build.

**Comment by Ordinary3** [comment] 2021-12-13 05:35
update your haxe

**Comment by MrTie-fixer** [comment] 2021-12-13 07:36
replace the storymenustate with the previous source code version storymenustate like 0.5b storymenustate (the most working storymenustate i think)

**Comment by tposejank** [comment] 2021-12-13 14:03
Download the source code here: https://github.com/ShadowMario/FNF-PsychEngine/archive/refs/heads/main.zip

**Comment by ShadowMario** [comment] 2021-12-13 18:33
Duplicate of #2049, #2038, #2028, #2027, #2026, #2024

**Closed by ShadowMario** 2021-12-13 18:33 UTC
Labels: bug
