### ISSUE TITLE
Not detect my sprites

### ISSUE THREAD

**Issue by UserRaix** [ShadowMario/FNF-PsychEngine#1073] opened 2021-11-16 19:49 UTC
### Please help

I have my character fully animated, the problem is that I made too many sprites (Idle, HEY, Scared, etc) and when generating the sprite sheet it wouldn't let me because there were many sprites, so I decided to do it like PixelBF, Sheets of different sprites, one for singing and another for the death animation

![image](https://user-images.githubusercontent.com/89859936/142054921-72a9f331-a410-4d4c-bcd2-b5678f659850.png)

So I made 2 json files

![image](https://user-images.githubusercontent.com/89859936/142055113-651105e8-86d0-47dd-ab89-8d21c9176a6e.png)

They are well programmed and everything else

But when it comes to playing everything normal, the problem is that it does not detect the death animation and instead puts the normal BF, could someone help me with this? I don't know much about programming

I am using a translator

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Don't edit anything at the moment, just add my character in the "mods" folder

**Comment by FuseIsHere813** [comment] 2021-11-16 22:54
Duplicate of #1008

**Comment by ShadowMario** [comment] 2021-11-17 23:44
^

**Closed by ShadowMario** 2021-11-17 23:44 UTC
Labels: help wanted
