### ISSUE TITLE
Character change event

### ISSUE THREAD

**Issue by ElitePhoenix** [ShadowMario/FNF-PsychEngine#1207] opened 2021-11-20 21:33 UTC
### Describe your problem here.

I wanted to use the character change event in the chart editor and but the Values (Value 1: Dad Value 2: ron) But when i test the chart it seems to change boyfriend instead, am i doing something wrong? Or maybe this is a bug

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by prokube** [comment] 2021-11-20 21:41
there is literally a character change event

**Comment by prokube** [comment] 2021-11-20 21:45
make 'Dad' lowercase lol. you shouldn't have to but do it anyway
![Screen Shot 2021-11-20 at 1 43 16 PM](https://user-images.githubusercontent.com/68293280/142741726-0a8b5a6b-cd70-4f27-a822-b3d82ee3f951.png)

**Comment by ElitePhoenix** [comment] 2021-11-20 21:53
> make 'Dad' lowercase lol. you shouldn't have to but do it anyway ![Screen Shot 2021-11-20 at 1 43 16 PM](https://user-images.githubusercontent.com/68293280/142741726-0a8b5a6b-cd70-4f27-a822-b3d82ee3f951.png)

https://user-images.githubusercontent.com/87148958/142741948-5fb0d834-6545-4cec-afa4-fc19ea2333b9.mp4

i tried that, sadly it still doesnt work

**Comment by KutikiPlayz** [comment] 2021-11-20 21:58
The first value has to be a number, so either 0, 1, or 2
I think the opponent is 1 but I'm not sure

**Comment by ShadowMario** [comment] 2021-11-21 06:22
Duplicate of #312

**Closed by ShadowMario** 2021-11-21 06:22 UTC
Labels: help wanted
