### ISSUE TITLE
Philly lights not working

### ISSUE THREAD

**Issue by IanSonicGachaVA** [ShadowMario/FNF-PsychEngine#9259] opened 2022-06-26 17:12 UTC
### Describe your bug here.

So I was about to test out the new Philly lights but however when I loaded the song I was editing the game crashed and will not shut off I used ALT F4, clicking "OK" and the game will not shut off

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2494)
PlayState.hx (line 2422)
PlayState.hx (line 1051)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BeastlyGhost** [comment] 2022-06-26 17:24
Philly Glow only works on Blammed, that's not a bug, it's on purpose so people won't overuse the hell out of it like they did with Blammed Lights

**Comment by fnfdemonboi314159** [comment] 2022-06-27 01:37
> Philly Glow only works on Blammed, that's not a bug, it's on purpose so people won't overuse the hell out of it like they did with Blammed Lights

huh, makes sense. It looked so cool, lol.

**Comment by frantastic24** [comment] 2022-06-27 01:38
Close this

**Closed** 2022-06-27 17:38 UTC
Labels: bug
