### ISSUE TITLE
yes, its me again.... im sorry for requesting soo much, but this is important for the new mods

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15369] opened 2024-08-20 19:55 UTC
### What feature do you want to get added on the **base** engine?

this is the thing.
in the 1.0 update i was soooooooo exited for play, BUT.. i needed a change stage event
and i didnt find any events for that on gamebanana, please, if you will make a hotfix or something add that event
DO IT FOR THE COMMUNITY :D
pleaaaseeeeee shadow mario
i love this engine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment] 2024-08-24 18:26
Duplicate of other rejected posts.

**Closed by ShadowMario** 2024-08-24 18:26 UTC
Labels: enhancement

**Comment by AlexTheGuy73** [comment] 2024-08-26 11:49
im never requesting again 💀
