### ISSUE TITLE
ABotSpeaker errors happening when trying to compile

### ISSUE THREAD

**Issue by zelofi** [ShadowMario/FNF-PsychEngine#15415] opened 2024-08-25 07:26 UTC
### Describe your bug here.

Whenever I try to compile Psych Engine, these errors appear and I have no clue why.
(Using the experimental tree)

### Command Prompt/Terminal logs (if existing)

```bash
[30;41m ERROR [0m source/states/stages/objects/ABotSpeaker.hx:3: characters 8-39

   3 | [2mimport [0m[1mfunkin.vis.dsp.SpectralAnalyzer[0m[2m;[0m
     |        [31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
     | Type not found : funkin.vis.dsp.SpectralAnalyzer

[30;41m ERROR [0m source/states/stages/objects/ABotSpeaker.hx:17: characters 15-31

  17 | [2m var analyzer:[0m[1mSpectralAnalyzer[0m[2m;[0m
     |               [31m^^^^^^^^^^^^^^^^[0m
     | Type not found : SpectralAnalyzer

[30;41m ERROR [0m source/states/stages/PhillyBlazin.hx:155: characters 8-11

 155 | [2m  abot.[0m[1msnd[0m[2m = FlxG.sound.music;[0m
     |        [31m^^^[0m
     | states.stages.objects.ABotSpeaker has no field snd

[30;41m ERROR [0m source/states/stages/PhillyStreets.hx:391: characters 9-18

 391 | [2m   abot.[0m[1mlookRight[0m[2m();[0m
     |         [31m^^^^^^^^^[0m
     | states.stages.objects.ABotSpeaker has no field lookRight

[30;41m ERROR [0m source/states/stages/PhillyStreets.hx:393: characters 9-17

 393 | [2m   abot.[0m[1mlookLeft[0m[2m();[0m
     |         [31m^^^^^^^^[0m
     | states.stages.objects.ABotSpeaker has no field lookLeft

[30;41m ERROR [0m source/states/stages/PhillyStreets.hx:400: characters 8-11

 400 | [2m  abot.[0m[1msnd[0m[2m = FlxG.sound.music;[0m
     |        [31m^^^[0m
     | states.stages.objects.ABotSpeaker has no field snd
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment] 2024-08-27 17:08
Duplicate of #15414

**Closed by ShadowMario** 2024-08-27 17:08 UTC
Labels: bug
