### ISSUE TITLE
problem with alt animations

### ISSUE THREAD

**Issue by PROJECTSMASH600** [ShadowMario/FNF-PsychEngine#4969] opened 2022-02-14 09:11 UTC
### Describe your problem here.

i tried to add alt animations and now the normal animations play the alt animations before the normal animations. nothing on youtube/github is helping. is it a problem with the .json or the .xml ore something else entirely?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

.json/.xml

**Comment by frantastic24** [comment] 2022-02-14 14:43
Show the .json

**Comment by PROJECTSMASH600** [comment] 2022-02-15 03:05
{
	"animations": [{
			"loop": false,
			"offsets": [
				-372,
				-209
			],
			"fps": 24,
			"anim": "singLEFT",
			"indices": [],
			"name": "aaaa-player left"
		},
		{
			"loop": false,
			"offsets": [
				-372,
				-209
			],
			"fps": 24,
			"anim": "singLEFT-alt",
			"indices": [],
			"name": "aaaa-player left-alt"
		},
		{
			"loop": false,
			"offsets": [
				-403,
				-234
			],
			"fps": 24,
			"anim": "singDOWN",
			"indices": [],
			"name": "aaaa-player down"
		},
{
			"loop": false,
			"offsets": [
				-403,
				-234
			],
			"fps": 24,
			"anim": "singDOWN-alt",
			"indices": [],
			"name": "aaaa-player down-alt"
		},
		{
			"loop": false,
			"offsets": [
				-409,
				-217
			],
			"fps": 24,
			"anim": "singUP",
			"indices": [],
			"name": "aaaa-player up"
		},
{
			"loop": false,
			"offsets": [
				-409,
				-217
			],
			"fps": 24,
			"anim": "singUP-alt",
			"indices": [],
			"name": "aaaa-player up-alt"
		},
		{
			"loop": false,
			"offsets": [
				-405,
				-219
			],
			"fps": 24,
			"anim": "singRIGHT",
			"indices": [],
			"name": "aaaa-player right"
		},
{
			"loop": false,
			"offsets": [
				-405,
				-219
			],
			"fps": 24,
			"anim": "singRIGHT-alt",
			"indices": [],
			"name": "aaaa-player right-alt"
		},
		{
			"loop": false,
			"offsets": [
				-409,
				-220
			],
			"fps": 24,
			"anim": "idle",
			"indices": [],
			"name": "aaaa-player idle"
		},
		{
			"loop": false,
			"offsets": [
				-409,
				-220
			],
			"fps": 24,
			"anim": "idle-alt",
			"indices": [],
			"name": "aaaa-player idle-alt"
		},
			{
				"loop": true,
				"offsets": [
					-372,
					-209
				],
				"fps": 24,
				"anim": "singLEFT-loop",
				"indices": [],
				"name": "aaaa-player left"
			},
			{
				"loop": true,
				"offsets": [
					-403,
					-234
				],
				"fps": 24,
				"anim": "singDOWN-loop",
				"indices": [],
				"name": "aaaa-player down"
			},
			{
				"loop": true,
				"offsets": [
					-409,
					-217
				],
				"fps": 24,
				"anim": "singUP-loop",
				"indices": [],
				"name": "aaaa-player up"
			},
			{
				"loop": true,
				"offsets": [
					-405,
					-219
				],
				"fps": 24,
				"anim": "singRIGHT-loop",
				"indices": [],
				"name": "aaaa-player right"
			},
			{
				"loop": true,
				"offsets": [
					-409,
					-220
				],
				"fps": 24,
				"anim": "idle-loop",
				"indices": [],
				"name": "aaaa-player idle"
			}
		],
		"no_antialiasing": false,
		"image": "characters/aaaa-player",
		"position": [
			0,
			0
		],
		"healthicon": "aaaa",
		"flip_x": true,
		"healthbar_colors": [
			255,
			221,
			0
		],
		"camera_position": [
			-160,
			170
		],
		"sing_duration": 5,
		"scale": 1.5
	}

**Comment by frantastic24** [comment] 2022-02-15 03:42
I don't see anything wrong with this file, and I'm not sure how to recreate the issue, could you send a video to get a better idea of it?

**Comment by PROJECTSMASH600** [comment] 2022-02-15 04:52
https://user-images.githubusercontent.com/81655526/153994832-3d45a1d7-6544-4527-ba91-f891fafa8287.mp4

**Comment by frantastic24** [comment] 2022-02-15 04:58
Have you checked to make sure your XML is correct?

**Comment by frantastic24** [comment] 2022-02-15 05:02
You can fix this by going through every normal animation and adding indices but it looks like the issue is in the XML

**Comment by Wither362** [comment] 2022-02-18 11:07
I had also that problem, if your character’s name is `aaaa-player`, simply remove the name, that is, that the `singLEFT-alt` is called `singLEFT-alt`, but that the animation it uses is not called in any way, that is, it is blank, and do that with all the other animations

**Comment by ShadowMario** [comment] 2022-02-22 19:51
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/825

**Closed by ShadowMario** 2022-02-22 19:51 UTC
Labels: help wanted
