### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EnderBoi201** [ShadowMario/FNF-PsychEngine#11377] opened 2022-12-03 06:08 UTC
### Describe your bug here.

StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 70)
PlayState.hx (line 3025)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i messed with Project.xml

**Comment by frantastic24** [comment] 2022-12-03 07:27
Not a bug
Duplicate of #9507

**Closed** 2022-12-03 07:41 UTC
Labels: bug
