### ISSUE TITLE
Song crashes with dadbattle spotlight

### ISSUE THREAD

**Issue by fenneey** [ShadowMario/FNF-PsychEngine#11098] opened 2022-11-02 22:32 UTC
### Describe your bug here.

I used the dadbattle spotlight inside of guns in week 7 and whenever I load up the song it crashes.
![image](https://user-images.githubusercontent.com/117320391/199614929-d5c640c6-6ff8-4b32-9036-316f6fc678a7.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment] 2022-11-02 23:02
Not a bug

**Comment by KingMB-XJ** [comment] 2022-11-02 23:56
Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.

**Comment by BeepSheep254** [comment] 2022-11-03 13:51
> Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.

yea, too bad no one made a dadbattle spotlight recreation event on lua

**Comment by Parsellol** [comment] 2022-11-03 15:11
its purposely hardcoded into week 1

**Comment by Gostar64** [comment] 2022-11-04 00:40
> > Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.
> 
> yea, too bad no one made a dadbattle spotlight recreation event on lua yet

https://gamebanana.com/tools/11052

**Comment by BeepSheep254** [comment] 2022-11-14 20:44
> > > Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.
> > 
> > 
> > yea, too bad no one made a dadbattle spotlight recreation event on lua yet
> 
> https://gamebanana.com/tools/11052

welp i spoke too soon

**Comment by TheKitBoi** [comment] 2022-11-15 07:08
close this issue

**Closed** 2023-07-19 17:31 UTC
Labels: bug
