### ISSUE TITLE
idle miss and no miss

### ISSUE THREAD

**Issue by ComaYami** [ShadowMario/FNF-PsychEngine#2148] opened 2021-12-15 00:49 UTC
### What feature do you want to get added on the base engine?

idk why it was removed btw if this isn't accepted thats okay i love how psych engine is cool
![image](https://user-images.githubusercontent.com/83175294/146102452-0067a9b9-6964-4bde-ae6b-93b533b32485.png)

**Comment by ShadowMario** [comment] 2021-12-15 01:51
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/2114
I didn't wanted to implement the idea so i closed the first issue.

**Closed** 2021-12-15 01:51 UTC
Labels: enhancement

**Comment by tposejank** [comment] 2021-12-15 02:18
Why the hell is this needed anyway, cant you just make one yourself and play it?

**Comment by ComaYami** [comment] 2021-12-15 15:09
> Duplicate of #2114 I didn't wanted to implement the idea so i closed the first issue.

ohh okay sorry i didn't know those things could be closed im new to github
