### ISSUE TITLE
noteTweenX, noteTweenY, and noteTweenDirection crashes the game when put into function onUpdate

### ISSUE THREAD

**Issue by NS-Unfair** [ShadowMario/FNF-PsychEngine#5987] opened 2022-02-28 19:57 UTC
### Describe your bug here.

This bug report is pretty self-explanatory. The title explains it all.

Here's a script that won't crash the game:
`
    local hp_loss = 0.0125
    local max_health = 1
    local min_health = 0.99999
    local rmin_health = 0.99999
    local clamp_hp_rate = 0.002
    local dir = 0
    songPos = 99
    _NoteIndX={[0]=0,0,0,0,0,0,0,0}

    function onCreate()
        _NoteIndX = {[0]=defaultOpponentStrumX0,defaultOpponentStrumX1,defaultOpponentStrumX2,defaultOpponentStrumX3,defaultPlayerStrumX0,defaultPlayerStrumX1,defaultPlayerStrumX2,defaultPlayerStrumX3}
        debugPrint('test')
    end

    function opponentNoteHit()
        health = getProperty('health')
        setProperty('health', math.max(health - hp_loss, rmin_health+0.00001))
        hp_loss=hp_loss+0.00005
    end

    function onUpdate()
        songPos = getSongPosition() or 0
        health = getProperty('health')
        -- Events
        if curStep==256 then
            max_health=2
            min_health=0
        end
        if curStep==1022 then
            max_health=1.5
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0008
        end
        if curStep==1408 then
            max_health=1
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0004
        end
        if curStep==1792 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==1919 then
            max_health=2
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.001
        end
        if curStep==2048 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==2176 then
            max_health=2
            min_health=1.75
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.2
        end
        local rmin_l = rmin_health
        rmin_health = lerp(rmin_health, min_health, clamp_hp_rate)
        if health < rmin_health and rmin_l==rmin_health then
            setProperty('health', 0)
        end
        if health <= rmin_health and rmin_l~=rmin_health then
            setProperty('health', rmin_health)
        end
        if health > max_health then
            setProperty('health', lerp(health, max_health, clamp_hp_rate))
        end
        if health <= max_health and health >= min_health then
            clamp_hp_rate=999
        end
    end

    function onUpdatePost()
        if curStep>=256 then
            for i=0,7,1 do
                noteTweenX('ntx'..i, i, _NoteIndX[i] + (math.sin(songPos/360)*25)+90, 0.2)
                noteTweenDirection('ntd'..i, i, (math.cos(songPos/360)*25)+90, 0.2)
            end
        end
    end

    function lerp(val,tar,rate)
        local res = val+((tar-val)*rate)
        if val<tar then
        res=math.min(res,tar)
        else
        res=math.max(res,tar)
        end
        return res
    end

    function onBeatHit() 
        
    end
`

Here's a script that will crash the game, this bug also affects earlier versions of Psych Engine:
`
    local hp_loss = 0.0125
    local max_health = 1
    local min_health = 0.99999
    local rmin_health = 0.99999
    local clamp_hp_rate = 0.002
    local dir = 0
    songPos = 99
    _NoteIndX={[0]=0,0,0,0,0,0,0,0}

    function onCreate()
        _NoteIndX = {[0]=defaultOpponentStrumX0,defaultOpponentStrumX1,defaultOpponentStrumX2,defaultOpponentStrumX3,defaultPlayerStrumX0,defaultPlayerStrumX1,defaultPlayerStrumX2,defaultPlayerStrumX3}
        debugPrint('test')
    end

    function opponentNoteHit()
        health = getProperty('health')
        setProperty('health', math.max(health - hp_loss, rmin_health+0.00001))
        hp_loss=hp_loss+0.00005
    end

    function onUpdate()
        songPos = getSongPosition() or 0
        health = getProperty('health')
        -- Events
        if curStep==256 then
            max_health=2
            min_health=0
        end
        if curStep==1022 then
            max_health=1.5
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0008
        end
        if curStep==1408 then
            max_health=1
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0004
        end
        if curStep==1792 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==1919 then
            max_health=2
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.001
        end
        if curStep==2048 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==2176 then
            max_health=2
            min_health=1.75
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.2
        end
        local rmin_l = rmin_health
        rmin_health = lerp(rmin_health, min_health, clamp_hp_rate)
        if health < rmin_health and rmin_l==rmin_health then
            setProperty('health', 0)
        end
        if health <= rmin_health and rmin_l~=rmin_health then
            setProperty('health', rmin_health)
        end
        if health > max_health then
            setProperty('health', lerp(health, max_health, clamp_hp_rate))
        end
        if health <= max_health and health >= min_health then
            clamp_hp_rate=999
        end
        if curStep>=256 then
            for i=0,7,1 do
                noteTweenX('ntx'..i, i, _NoteIndX[i] + (math.sin(songPos/360)*25)+90, 0.2)
                noteTweenDirection('ntd'..i, i, (math.cos(songPos/360)*25)+90, 0.2)
            end
        end
    end

    function onUpdatePost()
        
    end

    function lerp(val,tar,rate)
        local res = val+((tar-val)*rate)
        if val<tar then
        res=math.min(res,tar)
        else
        res=math.max(res,tar)
        end
        return res
    end

    function onBeatHit() 
        
    end
`

### Command Prompt/Terminal logs (if existing)

```bash
(A blank error message)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have made no changes to the build

**Comment by frantastic24** [comment] 2022-02-28 20:31
no crash here, either it's already fixed on source or it's a problem on your end

**Comment by NS-Unfair** [comment] 2022-02-28 20:38
@[frantastic24](https://github.com/frantastic24), try loading the script into the lore song in FNF VS Ourple Guy. Maybe you'll get a crash there?

**Comment by NS-Unfair** [comment] 2022-02-28 20:40
If it does crash, that means this bug has already been fixed if you tested it on the latest version of Psych Engine

**Comment by DragShot** [comment] 2022-02-28 21:01
I hadn't tested this script in particular, but having used Psych Engine 0.5.1 I can confirm that sending several logs via `debugPrint()`, at least once a step, crashes the game after about 15 seconds. I don't have the details since this thing does not emit a stack trace on error, so I can only guess some buffer is probably running out of space somewhere. Hopefully in the current builds this problem won't be present.

**Comment by frantastic24** [comment] 2022-02-28 21:23
It's true debugPrint crashes in some scenarios but it's not the case for tweens from my experience

**Comment by NS-Unfair** [comment] 2022-03-01 02:42
That might be what's happening with the tweens @DragShot, it might be a memory issue.

**Comment by NS-Unfair** [comment] 2022-03-03 06:18
I added function cancleTween to the script and it didn't crash; I think I know what the issue is.

**Comment by NS-Unfair** [comment] 2022-03-03 06:28
The script below fixed the crashing:

`
    local hp_loss = 0.0125
    local max_health = 1
    local min_health = 0.99999
    local rmin_health = 0.99999
    local clamp_hp_rate = 0.002
    local dir = 0
    local swing = false
    songPos = 0
    _NoteIndX={[0]=0,0,0,0,0,0,0,0}
    tagsDone = {}

    function onCreate()
        
    end

    function opponentNoteHit()
        health = getProperty('health')
        setProperty('health', math.max(health - hp_loss, rmin_health+0.00001))
        hp_loss=hp_loss+0.00005
    end

    function onUpdate()
        _NoteIndX = {[0]=defaultOpponentStrumX0,defaultOpponentStrumX1,defaultOpponentStrumX2,defaultOpponentStrumX3,defaultPlayerStrumX0,defaultPlayerStrumX1,defaultPlayerStrumX2,defaultPlayerStrumX3}
        songPos = getSongPosition() or 0
        health = getProperty('health')
        local rmin_l = rmin_health
        rmin_health = lerp(rmin_health, min_health, clamp_hp_rate)
        if health < rmin_health and rmin_l==rmin_health then
            setProperty('health', 0)
        end
        if health <= rmin_health and rmin_l~=rmin_health then
            setProperty('health', rmin_health)
        end
        if health > max_health then
            setProperty('health', lerp(health, max_health, clamp_hp_rate))
        end
        if health <= max_health and health >= min_health then
            clamp_hp_rate=999
        end
        cancleTween('ntx'..i)
        cancleTween('ntd'..i)
    end

    function onUpdatePost()
        -- Events
        if curStep==256 then
            max_health=2
            min_health=0
            swing=true
        end
        if curStep==1022 then
            max_health=1.5
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0008
            swing=false
        end
        if curStep==1408 then
            max_health=1
            min_health=0.5
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.0004
        end
        if curStep==1277 then
            swing=true
        end
        if curStep==1792 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==1919 then
            max_health=2
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.001
        end
        if curStep==2048 then
            max_health=0.25
            min_health=0
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.005
        end
        if curStep==2176 then
            max_health=2
            min_health=1.75
            setProperty('health', math.max(health, min_health))
            clamp_hp_rate=0.2
        end
        -- Swing Notes
        if swing then
            for i=0,7,1 do
                noteTweenX('ntx'..i, i, _NoteIndX[i] + (math.sin((songPos+(i*60))/360)*50), 0.2)
                noteTweenDirection('ntd'..i, i, (math.cos(songPos/360)*25)+90, 0.2)
            end
        end
        if curStep==1022 then
            ResetNotes()
        end
    end

    function ResetNotes()
        for i=0,7,1 do
            noteTweenX('ntx'..i, i, _NoteIndX[i], 0.2)
            noteTweenDirection('ntd'..i, i, 90, 0.2)
        end
    end

    function lerp(val,tar,rate)
        local res = val+((tar-val)*rate)
        if val<tar then
        res=math.min(res,tar)
        else
        res=math.max(res,tar)
        end
        return res
    end
`

The reason why the game is crashing is that it isn't canceling the tweens lmao. The program creates too many tweens.

**Closed** 2022-04-10 19:53 UTC
Labels: bug
