### ISSUE TITLE
This pop up

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10780] opened 2022-10-06 23:00 UTC
### Describe your bug here.

it crashes when i load the storymode

### Command Prompt/Terminal logs (if existing)

```bash
CHaxeToolkit\haxe\std/haxe/format/IsonParser.hx(line318)
C'\HaxeToolkit\haxe\std/haxe/format/IsonParser.hx(line99)
C\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx(line57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
StoryMenuState.hx (line 58)
flixel/FIxGame.hx (line 637)
flixel/FIxGame.hx (line 724)
flix el/FIxGame.hx (line 677)
flixel/FIxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Invalid char 105 at position 18
Please report this error to the GitHub page:
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything :netural_face:

**Comment by frantastic24** [comment] 2022-10-06 23:04
Not a bug
You fucked up your week file

**Comment by DisIsNOt** [comment] 2022-10-07 16:16
Now close this

**Comment by cooldude47980597** [comment] 2022-10-07 21:15
nah

**Comment by frantastic24** [comment] 2022-10-08 02:24
Read above
Close the issue

**Comment by cooldude47980597** [comment] 2022-10-08 04:08
ARE YOU FUCKING BLIND
I NEVER FUCKED MY WEEK FILE

**Comment by TheKitBoi** [comment] 2022-10-08 10:23
just send the god dam week file so I can fix ur
(Invalid char 105 at position 18

**Comment by cooldude47980597** [comment] 2022-10-08 17:01
https://gamejolt.com/games/plsdonate/753378 put this in fucking mods folder please

**Comment by cooldude47980597** [comment] 2022-10-08 17:04
Wait nvm don’t put it

**Closed** 2023-07-19 17:26 UTC
Labels: bug
