### ISSUE TITLE
HELP ME PLEASE

### ISSUE THREAD

**Issue by TonyRonii** [ShadowMario/FNF-PsychEngine#1058] opened 2021-11-15 18:53 UTC
### Describe your problem here.

IM WORKING ON MY FRIENDS MOD AND EVERYTIME I INPUT A NOTE CLICK OR KEYBOARD PRESS IT CRASHES WHAT DO I DO PLEASE HELP

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I editied a lot of things today Playstate, Achiements, Credits, AchiementsMenuState and some image assets

**Comment by Steviegt6** [comment] 2021-11-15 19:45
We can't see your code, how do you expect us to help you?

**Comment by TonyRonii** [comment] 2021-11-15 19:46
send the whole playstate code?

**Comment by Steviegt6** [comment] 2021-11-15 19:50
> send the whole playstate code?

It'd be nicer if you could create a diff between all modified code (i.e. publishing your code to GitHub).

**Comment by ShadowMario** [comment] 2021-11-18 00:01
Sounds like a duplicate of #343 
Plus no replies since 2 days so i will suppose OP fixed it.

**Closed by ShadowMario** 2021-11-18 00:01 UTC
Labels: help wanted
