### ISSUE TITLE
Uncaught error: Null object reference 

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#11326] opened 2022-11-27 05:00 UTC
### Describe your bug here.

well this bug appears during song that i put in "mods" folder in psych engine. who knows how to fix this bugggggggggggg
![Снимок экрана 2022-11-27 124957](https://user-images.githubusercontent.com/119149152/204119941-a976c57c-9a2c-47fa-aece-95e17b045aa6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-11-27 05:25
Not a bug
Note texture is missing sustain end animations

**Comment by vesel4ak** [comment] 2022-11-27 05:28
> 

then what should i do

**Comment by frantastic24** [comment] 2022-11-27 05:35
Add them to your note texture

**Comment by vesel4ak** [comment] 2022-11-27 05:41
> Add them to your note texture

kk

**Comment by frantastic24** [comment] 2022-11-27 06:45
You can close the issue

**Comment by vesel4ak** [comment] 2022-12-02 15:12
I DIDNT GET THIS

**Comment by TheKitBoi** [comment] 2022-12-02 16:12
and why

**Closed** 2022-12-31 08:48 UTC
Labels: bug
