### ISSUE TITLE
Achievements No Source Code..

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#8119] opened 2022-04-13 21:43 UTC
### What is your question?

Hello. I am just wondering, when the release of version 0.5.2, and 0.5.2h happened, there was this new folder in the mods folder. Other than the shaders one, it was the achievements folder.. I was searching the WHOLE internet to find an answer on how to make custom achievements in Psych Engine (no source code). And not even a SINGLE answer popped up. Basically what I am saying is, How do you make custom achievements in Psych Engine (no source code)??

**Comment by CrusherMods** [comment] 2022-04-13 21:49
You can't
The devs just forgot to remove the achievements and shaders folder
there is no way possible to add achievements without source code

**Comment by Pico8430** [comment] 2022-04-13 23:40
Like how just CrusherMods said, you can't exactly add softcoded achievements. BUT, there is a way to do so with a lua script, although it's more complex.

**Comment by ShadowMario** [comment] 2022-04-14 00:27
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/8019

**Closed by ShadowMario** 2022-04-14 00:27 UTC
Labels: question

**Comment by Nork1234** [comment] 2022-04-14 01:29
oh.. ok
