### ISSUE TITLE
How to change colour of time bar mid song Lua?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11970] opened 2023-02-23 15:26 UTC
### What is your question?

Up

**Comment by frantastic24** [comment] 2023-02-23 15:40
Duplicate of #8678
Please use the search feature

**Comment by NightmaresPlayz** [comment] 2023-02-24 00:30
Sorry

**Comment by NightmaresPlayz** [comment] 2023-02-24 00:31
This is midsong, not start of song

**Comment by frantastic24** [comment] 2023-02-24 00:35
setProperty works any time?

**Comment by TheKitBoi** [comment] 2023-02-24 00:36
> This is midsong, not start of song

ffs
```
function onStepHit()
    if curStep == number then
        setProperty('timeBar.color', hex color)
    end
end
```

**Comment by NightmaresPlayz** [comment] 2023-02-24 02:44
Are these in the stage file

**Comment by NightmaresPlayz** [comment] 2023-02-24 02:44
And is cursteps like the numbers in json that shows when events are or the square events in chart editor

**Comment by NightmaresPlayz** [comment] 2023-02-24 02:48
I got confused with the last stage change mid song

**Closed** 2023-02-24 03:29 UTC
Labels: question
