### ISSUE TITLE
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

### ISSUE THREAD

**Issue by gameygu-0213** [ShadowMario/FNF-PsychEngine#12962] opened 2023-07-31 17:19 UTC
### Describe your bug here.

i simply used the test debug batch file and it wont compile.

### Command Prompt/Terminal logs (if existing)

```bash
"BUILDING GAME
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

done.
Press any key to continue . . ."
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2023-07-31 17:50
Not a bug
Duplicate of #12828

**Closed** 2023-07-31 19:06 UTC
Labels: bug

**Comment by NodiaTheCat** [comment] 2024-07-26 15:50
i did that and now im getting this error
source/psychlua/CallbackHandler.hx:54: characters 3-4 : Missing ;
