### ISSUE TITLE
Allow character .json files to hold "p1 and p2 data"

### ISSUE THREAD

**Issue by MegaStarMari** [ShadowMario/FNF-PsychEngine#8408] opened 2022-04-30 19:40 UTC
### What feature do you want to get added on the **base** engine?

It be great if we could have p1 settings and p2 settings for the same character.json that'll make things like flipped note poses and  character and camera positioning a lot easier, so people don't have to create a second json just for when it's used for a different placement.

I have a mod with many characters, all of which have songs where they are either the player or the opponent, so it'd be very useful to have settings for both positions in the same file and cut out the time it'd take to make several "-p1" or "-p2" files for each one.

Thanks for reading!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment] 2022-04-30 20:07
Pretty sure this is a duplicate of multiple closed issues

**Comment by MegaStarMari** [comment] 2022-04-30 21:37
> Pretty sure this is a duplicate of multiple closed issues

Would you mind providing an example that I can refer to?

**Comment by frantastic24** [comment] 2022-04-30 22:01
#4242

**Comment by Stilic** [comment] 2022-05-02 11:29
no, just make a another character whose name is ending with `-player`.

**Comment by tylerandari12** [comment] 2022-05-07 23:59
> no, just make a another character whose name is ending with `-player`.

Also dont forget to swap the left and right animations... lol

**Closed** 2023-12-05 12:13 UTC
Labels: enhancement
