### ISSUE TITLE
Compiling error two billion and two

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#15299] opened 2024-08-14 01:33 UTC
### Describe your bug here.

So... the logs explain what I'm having a problem with.
Yes, I did censor my username.

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\*****\Downloads\FNF-PsychEngine-EK-0.4.6\FNF-PsychEngine-EK-0.4.6\FNF-PsychEngine\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes (EK version), but I don't remember.

**Comment by ShadowMario** [comment] 2024-08-16 17:53
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/14890

**Closed by ShadowMario** 2024-08-16 17:53 UTC
Labels: bug
