### ISSUE TITLE
can you add this note shit i added lol

### ISSUE THREAD

**Issue by THOBY555** [ShadowMario/FNF-PsychEngine#4724] opened 2022-02-11 08:20 UTC
### What feature do you want to get added on the **base** engine?

https://user-images.githubusercontent.com/71563419/153557863-1ef023ac-7fcd-488c-a50c-b9ee168e78aa.mp4

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ProgramerGamerZone** [comment] 2022-02-11 09:38
Can you tell me how you did it? I want it in source (or Lua if you made it in Lua) please

**Comment by ProgramerGamerZone** [comment] 2022-02-11 09:58
Ok can you like make a fork for it or something lol

**Comment by frantastic24** [comment] 2022-02-11 16:03
This should be a PR and not an issue but I'm pretty sure shadow already said this won't be a thing, you can even do this with Lua already

**Comment by Stilic** [comment] 2022-02-11 16:42
no, keep it to your fork.
also @ShadowMario can you close this useless issue please.

**Comment by ItsCapp** [comment] 2022-02-11 16:44
> no, keep it to your fork. also @ShadowMario can you close this useless issue please.

it's not an issue it's an enhancement,
and he's asking for different note textures on either side

**Comment by frantastic24** [comment] 2022-02-11 17:02
> it's not an issue it's an enhancement

Check what tab you're on

> and he's asking for different note textures on either side

Duplicate of several other issues, which have already been declined
This should be closed

**Closed** 2022-02-18 20:25 UTC
Labels: enhancement

**Comment by HIGGAMEON** [comment] 2022-05-29 19:08
this can easily be done in lua, it's not needed.
