### ISSUE TITLE
Hello, I Try To Compile the game but this appears

### ISSUE THREAD

**Issue by ITSJUSTDOGERELO** [ShadowMario/FNF-PsychEngine#11333] opened 2022-11-28 00:37 UTC
### What is your question?

source/Main.hx:75: characters 61-65 : Float should be Int
source/Main.hx:75: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:75: characters 61-65 : ... For function argument 'child'

**Comment by frantastic24** [comment] 2022-11-28 00:55
use the search feature before opening an issue #11308

**Comment by KookerFoxYT** [comment] 2023-03-14 22:07
> ### What is your question?
> source/Main.hx:75: characters 61-65 : Float should be Int source/Main.hx:75: characters 61-65 : ... For optional function argument 'updateFramerate' source/Main.hx:75: characters 61-65 : ... For function argument 'child'

this is literally a duplicate of several issues like #11308

AND CAN YOU PLEASE REPLACE THE MAIN.HX YOURE USING WITH THE LATEST ONE FROM THE SOURCE CODE

**Closed** 2023-07-19 18:19 UTC
Labels: question
