### ISSUE TITLE
modchart edior feature request

### ISSUE THREAD

**Issue by F1mpoPE** [ShadowMario/FNF-PsychEngine#15845] opened 2024-11-02 14:51 UTC
### What feature do you want to get added on the **base** engine?

So i was using a bit different engine due to cutscene not working in pre release and i saw that that engine uses Psych engine 0.6.3 as core and had modchart editor. so i have really big hope that you can add modchart editor in next or later update

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment] 2024-11-11 04:10
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/1415 and other similar issues

**Closed by ShadowMario** 2024-11-11 04:10 UTC
Labels: duplicate, enhancement, wont-do
