### ISSUE TITLE
crashes somehow

### ISSUE THREAD

**Issue by SIG7Pro** [ShadowMario/FNF-PsychEngine#9893] opened 2022-07-24 20:59 UTC
### Describe your bug here.

game crashes, using latest version, doesn't matter if i have any mods or not but it just crashes.
usually tested with fnf freeplay mod but also works without any mod
[PsychEngine_2022-07-24_16'57'57.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9176691/PsychEngine_2022-07-24_16.57.57.txt)
s (I think it was because of a folder I had in mods/, then when I removed all the folders from there it worked.)

### Command Prompt/Terminal logs (if existing)

```bash
StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 200)
MusicBeatState.hx (line 66)
PlayState.hx (line 2893)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```
### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just a macOS port someone made.

**Comment by frantastic24** [comment] 2022-07-24 21:22
seems like a duplicate of #9507

**Closed** 2023-07-19 17:11 UTC
Labels: bug
