### ISSUE TITLE
sqirra-rng?(Character editor)

### ISSUE THREAD

**Issue by Alejo5205** [ShadowMario/FNF-PsychEngine#13301] opened 2023-09-17 19:25 UTC
### Describe your bug here.

When I wanted to load a character's sprite, I got:
"C:\HaxeToolkit haxe\std/haxe/xml/Parser.hx (line 217)
Yo
C:\HaxeToolkit haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122) flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
states/editors/CharacterEditorState.hx (line 824)
states/editors/CharacterEditorState.hx (line 504)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2 Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng"
what I do?
error image:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/92231866/a972fb00-6150-4cf7-9c7b-56b1101d24f4)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2023-09-17 19:32
Duplicate of #9296

**Closed** 2023-12-05 12:09 UTC
Labels: bug
