### ISSUE TITLE
How to make animated background/stages?

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#988] opened 2021-11-12 16:00 UTC
### Read the title as it is the question.

mod build: lua

### What's 9+10?

21

### u stupid

:(

**Comment by FuseIsHere813** [comment] 2021-11-12 17:35
Duplicate of #480 #540 #788 #921 #968

Are you fucking kidding me???

**Comment by craftersshaft** [comment] 2021-11-12 19:01
But this isn't asking for a stage editor directly, just how to get the background to animate. People say it can be done with lua, but how?

**Comment by acap09** [comment] 2021-11-12 19:22
> Duplicate of #480 #540 #788 #921 #968
> 
> Are you fucking kidding me???

Bro, I'm not asking for a stage editor, I'm just asking on how to make an animated background/stages. (LUA CODING)

**Comment by craftersshaft** [comment] 2021-11-12 19:29
figured it out by watching bbpanzu's tutorial, the code basically goes like this:

`	makeAnimatedLuaSprite('stageback', 'newsourbg', -585, 50);
	addAnimationByPrefix('stageback', 'loop', 'halloweem bg',24,true);`

stageback is the sprite id, newsourbg is the png/xml under the images folder (the prefix thing didnt want to work for me), loop is the animation name, halloweem bg is the xml animation id, 24 is the framerate, the true at the end is if it loops or not

**Comment by FuseIsHere813** [comment] 2021-11-12 22:57
> > Duplicate of #480 #540 #788 #921 #968
> > Are you fucking kidding me???
> 
> Bro, I'm not asking for a stage editor, I'm just asking on how to make an animated background/stages. (LUA CODING)

aight sorry for the mess.

**Comment by ShadowMario** [comment] 2021-11-13 02:12
Lua Script API has an example

**Closed by ShadowMario** 2021-11-13 02:12 UTC
Labels: question

**Comment by acap09** [comment] 2021-11-19 18:55
unimportant necropost

**Comment by acap09** [comment] 2021-11-19 18:55
anyways, ok ill check lua script API

**Comment by melocotonwaztaken** [comment] 2022-08-07 14:45
u
