### ISSUE TITLE
VORTEX EDITOR in the charter menu.

### ISSUE THREAD

**Issue by kitinho** [ShadowMario/FNF-PsychEngine#2008] opened 2021-12-12 12:45 UTC
### What is your question?

i want to know all about this setting on charter editor
![image](https://user-images.githubusercontent.com/69540352/145712730-dc5cda0f-a484-4bc0-b830-e304a8d11ade.png)

and this 
![image](https://user-images.githubusercontent.com/69540352/145712746-9808bf44-88dd-4774-9410-d6ad9a2495a3.png)
if theres no problem

**Comment by AToska21** [comment] 2021-12-12 12:49
yeah me too ima keep this open

**Comment by ShadowMario** [comment] 2021-12-13 02:41
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/1924

**Closed by ShadowMario** 2021-12-13 02:41 UTC
Labels: question
