### ISSUE TITLE
TeaCall not found, help pls

### ISSUE THREAD

**Issue by benja64** [ShadowMario/FNF-PsychEngine#14897] opened 2024-06-14 22:51 UTC
### Describe your problem here.

when i try to compile the code, it shows this error #
![uigbeafbhusadu](https://github.com/ShadowMario/FNF-PsychEngine/assets/93892668/99d8c98c-1132-41e0-80aa-7785dcdec084)

i tried everything, it still doesnt work

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by benja64** [comment] 2024-06-14 22:53
> ### Describe your problem here.
> when i try to compile the code, it shows this error # ![uigbeafbhusadu](https://private-user-images.githubusercontent.com/93892668/339923060-99d8c98c-1132-41e0-80aa-7785dcdec084.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDU4MDEsIm5iZiI6MTcxODQwNTUwMSwicGF0aCI6Ii85Mzg5MjY2OC8zMzk5MjMwNjAtOTlkOGM5OGMtMTEzMi00MWUwLTgwYWEtNzc4NWRjZGVjMDg0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDIyNTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjRlY2VkOGMyZjhkNjAxMmY1NGFlMWUyNmJkYThlYjlkZDk5MjVhYTI5NTUzMGM1ODQ3MDVhZjM2OTAzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FEyVbaPscsg-4rm2FOb1NktTR_t4XH2pXBgaVoPFqjg)
> 
> i tried everything, it still doesnt work
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no

![xc zcz](https://github.com/ShadowMario/FNF-PsychEngine/assets/93892668/a1e6397a-2970-46b1-89e0-9453fb75eebe)

**Comment by ShadowMario** [comment] 2024-06-16 18:37
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/14852

**Closed by ShadowMario** 2024-06-16 18:37 UTC
Labels: help wanted
