### ISSUE TITLE
An easier way to make custom menus whiout coding

### ISSUE THREAD

**Issue by ModdedFNF** [ShadowMario/FNF-PsychEngine#7346] opened 2022-03-20 18:31 UTC
### What feature do you want to get added on the **base** engine?

I'm making an fnf mod and one of the things I want my mod has is a custom menu, like the main menu options moved to one side or the weeks in the side and the backround in the other side, and looking a lot of tutorials in youtube, downloading a lot of things and coding a lot, I discovered that my pc can't compile psych engine, so, I ask for myself "what if the engine has a better way to make custom menús??" And here it is, making a suggestion for that, hope you read me and accept my idea

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by Pico8430** [comment] 2022-03-20 18:35
I don't really think they are going to add it. + You failed the test.

**Comment by frantastic24** [comment] 2022-03-20 18:57
Duplicate of MANY other posts, and failed the test
Massive L

**Comment by ModdedFNF** [comment] 2022-03-20 19:30
Which test?

**Comment by tylerandari12** [comment] 2022-03-20 22:00
They said in the beginning that theyre not gonna add 4k support, Stage editor, and stuff like that.
You were supposed to put that in for what shouldnt be submitted.

But dont worry, I did it the first time too.

**Comment by Pico8430** [comment] 2022-03-20 23:34
> Which test?

![Screenshot_20220320-183242~2](https://user-images.githubusercontent.com/91833725/159190818-bd4c22ff-1986-4e73-a3c9-4df105dfe61e.png)

**Closed** 2022-03-21 13:00 UTC
Labels: enhancement
