### ISSUE TITLE
removeHScript crashing game when song ends

### ISSUE THREAD

**Issue by BobbyDrawz** [ShadowMario/FNF-PsychEngine#15610] opened 2024-10-01 11:31 UTC
### Describe your bug here.

shit keeps crashing my game when a song ends, i want it to work the way it did in 0.7.3.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BobbyDrawz** [comment] 2024-10-01 18:39
> @ShadowMario dupe pls remove

i swear i typed this myself

**Comment by ShadowMario** [comment] 2024-10-24 17:20
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/15611

**Closed by ShadowMario** 2024-10-24 17:20 UTC
Labels: bug
