### ISSUE TITLE
error with menu

### ISSUE THREAD

**Issue by alternate2757** [ShadowMario/FNF-PsychEngine#11213] opened 2022-11-11 16:18 UTC
### Describe your bug here.

So, basically i was porting vs dave, then i found this in the game
![2022-11-11](https://user-images.githubusercontent.com/118006859/201383757-73bdad38-ba75-4490-9e20-ba4a23dbe69f.png)
I was wondering, why are there hashtags in the text?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added some chars, some charts, and some additional details.

**Comment by frantastic24** [comment] 2022-11-11 16:21
Not a bug
Update your alphabet texture

**Comment by alternate2757** [comment] 2022-11-11 16:26
> Not a bug Update your alphabet texture

i replaced the old data folder with the new one and that didnt help.

**Comment by frantastic24** [comment] 2022-11-11 16:42
Data folder doesn't have textures

**Comment by alternate2757** [comment] 2022-11-11 16:44
the how do i update the texture

**Comment by frantastic24** [comment] 2022-11-11 16:45
Find it in images

**Comment by alternate2757** [comment] 2022-11-11 16:46
yeah, this is all i got...
![2022-11-11 (2)](https://user-images.githubusercontent.com/118006859/201388882-f34374a7-0b88-4865-9466-01b9ff75ad7d.png)

**Comment by alternate2757** [comment] 2022-11-11 16:47
wait i found out a problem

**Comment by alternate2757** [comment] 2022-11-11 16:47
> wait i found out a problem

theres a copy of alphabet in mod/images, i am stupid.

**Comment by TheKitBoi** [comment] 2022-11-11 17:11
you can close this
![close the dam issue](https://user-images.githubusercontent.com/84044666/201393456-88aadc20-e0f8-4d43-9219-4612ce990ae0.gif)

**Closed** 2023-05-19 21:24 UTC
Labels: bug
