### ISSUE TITLE
song not loading

### ISSUE THREAD

**Issue by dcsiscool** [ShadowMario/FNF-PsychEngine#1406] opened 2021-11-27 15:05 UTC
### Describe your problem here.

hello there, when i go to my mods folder, my mod and then songs and put my song folder in there, i load it in psych engine and it does not work.

i tried in the normal songs folder with all the vanilla songs, nothing. the files are all ogg and every time i load the song it just says 0/0. please help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i made a week image, some other week stuff and added my song folder

**Comment by NotEpik** [comment] 2021-11-27 15:40
Can I see the image of it not working please, I don't understand bruh

also, is songs and data folder in the /mods?

**Comment by dcsiscool** [comment] 2021-11-27 16:42
![image](https://user-images.githubusercontent.com/54508700/143689684-5ef9bae5-dbde-4473-8d9e-ff5c33505f13.png)

**Comment by ShadowMario** [comment] 2021-11-27 22:09
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/1401

**Comment by ShadowMario** [comment] 2021-11-27 22:10
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/1401

**Closed by ShadowMario** 2021-11-27 22:09 UTC
Labels: help wanted
