### ISSUE TITLE
uhhh how can i fix this?

### ISSUE THREAD

**Issue by guizinhomartinez** [ShadowMario/FNF-PsychEngine#2149] opened 2021-12-15 00:55 UTC
### Describe your bug here.

uhhh idk what to say here since idk what the bug is saying

maybe a image of it can help
![image](https://user-images.githubusercontent.com/81656897/146102961-5d12cb67-0d6c-452e-aedc-032e700427a9.png)

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed the scoretxt position and disabled the function of you being able to change the rating and numscore position, i alredy did this in 0.5 pre release and it worked fine

**Comment by tposejank** [comment] 2021-12-15 01:29
duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 ***update your haxe.***

**Closed** 2021-12-15 01:52 UTC
Labels: bug
