### ISSUE TITLE
Psych Engine crashes while trying to change sprite sheet in character editor.

### ISSUE THREAD

**Issue by SlightlyCreative** [ShadowMario/FNF-PsychEngine#10988] opened 2022-10-24 23:34 UTC
### Describe your bug here.

![image](https://user-images.githubusercontent.com/116606678/197649527-06b02f72-5d28-4008-9e17-7dbcdfc876d9.png)

So, I'm trying to make a new player character. But when I change the sprite sheet file name and reload the image, the game crashes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment] 2022-10-24 23:40
Duplicate of #10834

**Comment by DestDeHat** [comment] 2022-10-29 21:55
the spritesheet is missing an xml or has a different xml type which isn't supported by haxe

**Closed** 2023-07-19 17:31 UTC
Labels: bug
