### ISSUE TITLE
Add option for quant notes?

### ISSUE THREAD

**Issue by Brandon32204** [ShadowMario/FNF-PsychEngine#11113] opened 2022-11-03 22:42 UTC
### What feature do you want to get added on the **base** engine?

Add option for quant notes, they are basically just color coding the notes to snaps instead of the direction, im not sure if this falls under what im not suppose to ask for but the retrospectre mod has already added this into psych, so maybe you could ask them if they could put that stuff into the base engine

(i know its prob not that simple and maybe everything could break from this one simple seeming change)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment] 2022-11-04 00:11
there's a mod that replicate quant notes in lua 
look in scripts or extra script folder
https://gamebanana.com/mods/374977

**Comment by BeastlyGhost** [comment] 2022-11-04 15:13
duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/60

**Closed** 2022-11-14 21:04 UTC
Labels: enhancement
