### ISSUE TITLE
Stage change (EVENT)

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15379] opened 2024-08-21 08:31 UTC
### What feature do you want to get added on the **base** engine?

Im making a obituary cover and i cant change the bg on the exe part bc i need a change bg event
And since Psych Engine changed its way of doing stages (from putting a .lua and a json, to just a json) I can't change the stage anymore, so could you add an event to change the background in the middle of the song, please?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by PaodeMelYTBR** [comment] 2024-08-21 11:49
I'm having this problem too lol

**Comment by PDL2CGamejolt** [comment] 2024-08-21 22:25
Can you please stop requesting this? This is prolly why he's been ignoring it.

**Comment by ADA-Funni** [comment] 2024-08-22 18:24
The method to access stage objects is `game.getLuaObject('objName')` in HScript, and `'objName'` in Lua.

**Comment by ShadowMario** [comment] 2024-08-24 18:21
Duplicate of a bunch of other posts.

**Closed by ShadowMario** 2024-08-24 18:21 UTC
Labels: enhancement
