### ISSUE TITLE
spooky fla?

### ISSUE THREAD

**Issue by 7oltan** [ShadowMario/FNF-PsychEngine#812] opened 2021-11-04 13:27 UTC
### What needs to be documented?

where is the spooky kids fla. bc i want the "Hey!" anim for a mod

**Comment by HiroOfc** [comment] 2021-11-04 19:13
ShadowMario already answered this at #377

**Comment by FuseIsHere813** [comment] 2021-11-04 23:22
Duplicate of #377

**Comment by ShadowMario** [comment] 2021-11-05 21:25
Duplicate of #377

**Closed by ShadowMario** 2021-11-05 21:25 UTC
Labels: documentation
