### ISSUE TITLE
Character Switch

### ISSUE THREAD

**Issue by ninjaninja140** [ShadowMario/FNF-PsychEngine#777] opened 2021-11-02 17:32 UTC
### Describe your bug here.

So basically when i was making a psych engine port of vs hank accelerant every time i changed the gf sprites to tricky they would change bf instead of gf. Anyone know if this is fixable or if its just a bug?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only edits were custom characters.

**Comment by ItsCapp** [comment] 2021-11-02 17:43
0 is bf, 1 is opponent, 2 is gf.
in the value that changes the character, type 2

**Comment by ninjaninja140** [comment] 2021-11-02 17:44
> 
> 
> 0 is bf, 1 is opponent, 2 is gf. in the value that changes the character, type 2

Oh because i was using events to change them lol

**Comment by ShadowMario** [comment] 2021-11-02 23:42
Duplicate of #735 and #591 
Plus, if you already figured out your issue then why didn't you close this issue???????

**Closed by ShadowMario** 2021-11-02 23:42 UTC
Labels: bug
