### ISSUE TITLE
bug in freeplay

### ISSUE THREAD

**Issue by AnthonyYTB** [ShadowMario/FNF-PsychEngine#10908] opened 2022-10-19 17:41 UTC
### Describe your bug here.

So I ported my mod from 0.6.2 to 0.6.3, and uh, all the songs names in freeplay are replaced by %, all of 'em. (Here's a screenshot.)
![Capture d’écran 2022-10-19 193557](https://user-images.githubusercontent.com/96132067/196764948-ced9cd59-c8e0-47f9-bce6-93b22cf319d4.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing expect in the mod folders.

**Comment by AnthonyYTB** [comment] 2022-10-19 17:47
I just noticed that the achievements are glitched too.

**Comment by frantastic24** [comment] 2022-10-19 17:51
Duplicate of #10905

**Closed** 2022-10-19 18:59 UTC
Labels: bug
