### ISSUE TITLE
Problems to export, again

### ISSUE THREAD

**Issue by Carlnal** [ShadowMario/FNF-PsychEngine#11301] opened 2022-11-24 03:45 UTC
### Describe your problem here.

when I try to export the game, I get the following message.
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
![Captura de pantalla (133)](https://user-images.githubusercontent.com/95714446/203689261-2a715c41-0f20-48fd-9638-bc1702425901.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment] 2022-11-24 04:08
duplicate of #11292 + #11293

**Comment by ACrazyTown** [comment] 2022-11-24 15:05
You're using the Flixel 5.0, which came out a few days ago. Either revert back to Flixel 4.11 or follow the [migration guide](https://github.com/HaxeFlixel/flixel/wiki/Flixel-5.0.0-Migration-guide)

**Comment by Carlnal** [comment] 2022-11-26 03:10
> Estás usando el Flixel 5.0, que salió hace unos días. Vuelve a Flixel 4.11 o sigue la [guía de migración](https://github.com/HaxeFlixel/flixel/wiki/Flixel-5.0.0-Migration-guide)

how did you revert to version 4.11?

**Comment by ACrazyTown** [comment] 2022-11-26 06:18
> > Estás usando el Flixel 5.0, que salió hace unos días. Vuelve a Flixel 4.11 o sigue la [guía de migración](https://github.com/HaxeFlixel/flixel/wiki/Flixel-5.0.0-Migration-guide)
> 
> how did you revert to version 4.11?

`haxelib set flixel 4.11.0`

**Closed** 2023-07-19 15:55 UTC
Labels: help wanted
