### ISSUE TITLE
BRah

### ISSUE THREAD

**Issue by K1N00** [ShadowMario/FNF-PsychEngine#12632] opened 2023-06-26 22:58 UTC
### Describe your bug here.

i keep getting 
PlayState.hx (line 2614)
PlayState.hx (line 2469)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

when i use a custom stage, and ive allready tried deleteing every event and such but it keeps showing this and idk why

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no response

**Comment by frantastic24** [comment] 2023-06-26 23:08
Duplicate of #12124
You can look up issues before posting

**Comment by K1N00** [comment] 2023-06-26 23:14
> Duplicate of #12124 You can look up issues before posting

i did, and like i said i deleted every event too and the stage still wouldnt work. its notphilly glow. or dad battle light

**Comment by frantastic24** [comment] 2023-06-27 00:29
It is what the error says
Can't tell much else without files

**Closed** 2023-07-19 18:59 UTC
Labels: bug
