### ISSUE TITLE
I think I'm a bug magnet

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9429] opened 2022-07-01 18:07 UTC
### Describe your bug here.

Porting Tabi because it's the third time I'm saying that... I've changed the name of a character for some adjustments adn everything and then I got this
![image](https://user-images.githubusercontent.com/101997612/176947618-6f092ffd-e745-474d-b1f5-9b55e8eed49e.png)
I perfectly know why it happened but it say I must report this error here.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

noooooooooooo, just a character's name

**Comment by Galbio** [comment] 2022-07-01 18:08
So litteraly 1 minute after the post I've understood... if the character's pgn and xml name are different you get the error

**Comment by ZeitHeld** [comment] 2022-07-01 18:15
porting from older mods has to be considered. some events might not handle it well
But if the issue is solved, as you know the problem now, you can close this issue

**Closed** 2022-07-01 18:19 UTC
Labels: bug
