### ISSUE TITLE
Cant make note assets using flash cs6

### ISSUE THREAD

**Issue by jan-doez-animationz** [ShadowMario/FNF-PsychEngine#11211] opened 2022-11-11 13:42 UTC
### Describe your bug here.

Bassically i tried making note assets using flash cs6 and it didnt work
i litterally tried everything diffrent encodings the default xml nothing work 
please somebody who knows anything about this help
all i kept getting was this : 
trumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 66)
PlayState.hx (line 2878)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All i did is mainly add some songs and made sprites

**Comment by frantastic24** [comment] 2022-11-11 13:56
Duplicate of #9507

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:30
Found the way to fix it bassically there are 2 copies of arrows that you hit a movie clip and and a graphic most people go into the arrow assets and select everything and generate a spritesheet boom the game crashes

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:41
wrong it still doesnt work

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:43
waittt i was wrong i might just need to readd the weird long note press thing that i thought was the problem

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:50
got the same crash again D:

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:53
I DONT UNDERSTAND THE CRASH WHY DOES IT KEEP CRASHING

**Comment by jan-doez-animationz** [comment] 2022-11-11 20:57
WHY THE FUCK ARE THE NOTE ASSETS SO WEIRDLY MADE

**Comment by jan-doez-animationz** [comment] 2022-11-11 21:07
i tried everything fixing anything that was wrong nothing worked same crash I DONT GET IT ima go to sleep if i tried more i'd go insane

**Comment by frantastic24** [comment] 2022-11-11 21:31
Don't reopen, it's a duplicate and you never even posted your files

**Comment by jan-doez-animationz** [comment] 2022-11-12 09:30
![NOTE_assets6](https://user-images.githubusercontent.com/115642016/201467999-67f76531-c08e-40d6-a2df-5f2dce20338a.png)
here are the assets and dont reopen what?

**Comment by jan-doez-animationz** [comment] 2022-11-12 09:31
oh yeah i noticed the problem

**Comment by jan-doez-animationz** [comment] 2022-11-12 09:46
i dont get it

**Comment by jan-doez-animationz** [comment] 2022-11-12 09:46
![NOTE_assets7](https://user-images.githubusercontent.com/115642016/201468543-435ab24b-3f45-4372-a843-6c013626f8e9.png)

**Comment by DevFregnub** [comment] 2022-11-18 17:02
Flash CS6 Typically doesnt work with fnf psych, no idea why. Maybe migrate to CS5.5

**Comment by QuetzalcoutlDev** [comment] 2022-11-19 01:57
> ### Describe your bug here.
> Bassically i tried making note assets using flash cs6 and it didnt work i litterally tried everything diffrent encodings the default xml nothing work please somebody who knows anything about this help all i kept getting was this : trumNote.hx (line 139) flixel/group/FlxGroup.hx (line 175) flixel/group/FlxGroup.hx (line 175) flixel/addons/ui/FlxUIState.hx (line 212) MusicBeatState.hx (line 66) PlayState.hx (line 2878) flixel/FlxState.hx (line 203) flixel/FlxGame.hx (line 747) flixel/FlxGame.hx (line 677) flixel/FlxGame.hx (line 551) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> All i did is mainly add some songs and made sprites

@jan-doez-animationz 
the problem is that the encoding of the .xml files exported in Flash CS6 is UTF-16 and Psych Engine (HaxeFlixel) uses and only allows the utf-8 encoding, I use Flash CS6 and I will tell you what I do so that you can use sprites exported in Flash CS6

1. I export the sprite
2. I open the exported .xml with my code editor (Sublime Text, although it can also be Visual Studio Code or Atom)

3.And I save the .xml with utf-8 encoding with BOM (in the save tab there is an option that says save with encoding...)

And ready you can use the sprite (in your case the notes)

Note: You should not modify the .xml at all, just save it again but with its new encoding.

**Closed** 2023-07-19 17:54 UTC
Labels: bug
