### ISSUE TITLE
problems with the hxdiscord_rpc library

### ISSUE THREAD

**Issue by thegreatskep** [ShadowMario/FNF-PsychEngine#13926] opened 2024-01-07 02:43 UTC
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

so im trying to compile the engine and the **only** error im getting is "Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?" i keep installing it over and over and it keeps giving me the same error. why is this happening?

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i havent edited anything yet besides project.xml, in which i only edited the line with the window title.

**Comment by ShadowMario** [comment] 2024-01-09 04:59
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/13771

**Closed by ShadowMario** 2024-01-09 04:59 UTC
Labels: bug
