### ISSUE TITLE
Note speed is always the same, no matter what song

### ISSUE THREAD

**Issue by SE2607** [ShadowMario/FNF-PsychEngine#10242] opened 2022-08-19 03:44 UTC
### Describe your bug here.

For some reason, each time I play any song on psych the note speed is super low, and when I change it through the chart editor the note speed stays the same
It's not even a compiled build or anything, it's literally with any mod or song I try to play
I have also tried with other engines like Kade Engine and the note speed is normal, so I believe it's a psych engine issue

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Like I said, it's with every song I try to play (wether from base game or mod song) and I don't have Psych compiled at all

**Comment by frantastic24** [comment] 2022-08-19 04:00
Duplicate of several issues
Press Control in Story/Freeplay

**Comment by Mastercopper2346** [comment] 2022-08-19 14:45
> Duplicate of several issues
> Press Control in Story/Freeplay

and change it to multiplicative, and to x1

**Closed** 2023-07-19 17:18 UTC
Labels: bug
