### ISSUE TITLE
Linux Builds

### ISSUE THREAD

**Issue by Erisfiregamer1** [ShadowMario/FNF-PsychEngine#1035] opened 2021-11-14 16:01 UTC
### What feature do you want to get added on the base engine?

Build Psych for Linux, so we can experience FNF without crashing.
(cmon man I want to suffer on Accelerant Hank already)

**Comment by Erisfiregamer1** [comment] 2021-11-14 16:02
before you say you can't do it yourself, workflows.
just use that.

**Comment by ShadowMario** [comment] 2021-11-16 03:12
Duplicate of #219

**Closed by ShadowMario** 2021-11-16 03:12 UTC
Labels: enhancement

**Comment by Erisfiregamer1** [comment] 2021-11-16 21:04
Not a duplicate. I would HAPPILY run the actions for the builds!
