### ISSUE TITLE
'Change Character' for 'Dad' event not working. (I'm using v0.4.2) (Using Mods folder)

### ISSUE THREAD

**Issue by FanKid** [ShadowMario/FNF-PsychEngine#901] opened 2021-11-09 04:41 UTC
### Describe your bug here.

I was trying to make a BETADCIU song 'Nyeh' playable by TJ255, but when I tried changing the 'Dad' character, it only changes the 'BF' character. Is this a bug that is should be fixed?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just the mods folder.

**Comment by cfgexe** [comment] 2021-11-09 04:45
where did you try to edit it from?

**Comment by FanKid** [comment] 2021-11-09 04:52
@cfgexe I just used the chart editor by placing event notes on the side and tested it using Henry and Tankman as the 'Dad' character and it's only changing the 'BF' character.

**Comment by Bruno215Brochado** [comment] 2021-11-09 09:11
You need to write '1' in value 1 to change opponent character

**Comment by FanKid** [comment] 2021-11-09 12:42
@Bruno215Brochado Dang, I forgot, also I should've read the desc more. Thanks!

**Comment by acap09** [comment] 2021-11-09 14:44
I THINK THIS ISSUE IS SOLVED, so please close this

**Comment by NotEpik** [comment] 2021-11-10 03:50
0 = bf
1 = dad
2 = gf

**Comment by FuseIsHere813** [comment] 2021-11-10 14:32
Yeah close this issue bozo.

**Comment by ShadowMario** [comment] 2021-11-10 17:10
Duplicate of #312, close your motherfucking issue if you're done with it.

**Closed by ShadowMario** 2021-11-10 17:10 UTC
Labels: bug
