### ISSUE TITLE
i need some help please

### ISSUE THREAD

**Issue by sebby09559** [ShadowMario/FNF-PsychEngine#10898] opened 2022-10-19 02:35 UTC
### Describe your problem here.

its been a long time since i last used psych engine and had to build the game how do i fix this error 
![image](https://user-images.githubusercontent.com/42832765/196583916-9b07fbad-9ac0-4fc9-878b-ba8dd0400fdb.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

help

**Comment by NotNimu** [comment] 2022-10-19 02:38
Ok but send us what’s on those lines or we can fix it

**Comment by frantastic24** [comment] 2022-10-19 02:48
Duplicate

**Comment by sebby09559** [comment] 2022-10-19 03:03
duplicate what?

**Comment by sebby09559** [comment] 2022-10-19 03:09
![Uploading image.png…]()

**Comment by sebby09559** [comment] 2022-10-19 03:10
> Ok but send us what’s on those lines or we cant fix it

![image](https://user-images.githubusercontent.com/42832765/196588481-e7318eb8-2bd9-4f23-a594-e3a8e0480aa7.png)

**Comment by frantastic24** [comment] 2022-10-19 03:54
>duplicate what?

Duplicate of several other issues, there is a search feature

**Comment by MemeHoovy** [comment] 2022-10-19 05:34
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by MemeHoovy** [comment] 2022-10-19 05:34
> ### Describe your problem here.
> its been a long time since i last used psych engine and had to build the game how do i fix this error ![image](https://user-images.githubusercontent.com/42832765/196583916-9b07fbad-9ac0-4fc9-878b-ba8dd0400fdb.png)
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> help

`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

**Closed** 2023-07-19 15:50 UTC
Labels: help wanted
