### ISSUE TITLE
Lime Test Windows Error (Song.hx:65: characters 27-41 : Array access is not allowed)

### ISSUE THREAD

**Issue by TechnicTom22** [ShadowMario/FNF-PsychEngine#2074] opened 2021-12-13 19:15 UTC
### Describe your bug here.

When I attempt to run Psych Engine it gives me an error of:
"source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }"

### Command Prompt/Terminal logs (if existing)

```bash
PS E:\Documents\FNF-PsychEngine-main> lime test windows
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added a new character to character list

**Comment by leobro1106** [comment] 2021-12-13 19:19
I had the same problem

**Comment by DaBanana64** [comment] 2021-12-13 19:19
Update your [haxe](https://haxe.org/download/).

**Comment by tposejank** [comment] 2021-12-13 20:21
Jesus, UPDATE YOUR FUCKING HAXE OMG

**Comment by SanicBTW** [comment] 2021-12-13 22:08
Guys just convert the array to dynamic for those who have an old haxe ver

**Comment by FuseIsHere813** [comment] 2021-12-15 04:19
duplicate of #2053, #2049, #2038, #2028, #2027, #2026, #2024 #2067 #2074

**update your haxe, stop using 4.1.5.**

**Closed** 2021-12-15 04:45 UTC
Labels: bug

**Comment by uiojaafdosijfafdssf** [comment] 2022-01-04 23:57
none of this is helping, i DID update my haxe, its at version 4.2.4. but i still get the same error. i changed nothing. also i use windows 11 if that changes anything.
