### ISSUE TITLE
Invalid char 34 at position 108

### ISSUE THREAD

**Issue by NewbieTrustMe** [ShadowMario/FNF-PsychEngine#12075] opened 2023-03-12 07:50 UTC
### Describe your bug here.

For some reason, I can't access the Mods menu! It just crashes with this error:

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 96)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
ModsMenuState.hx (line 734)
ModsMenuState.hx (line 329)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 34 at position 108
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I have no idea what is going on here.
By the way, I have 2 folders which are mods. They are in the well, mods folder.
They don't have any scripts.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment] 2023-03-12 14:12
Not a bug
There is a broken mod pack json

**Comment by TheKitBoi** [comment] 2023-03-12 15:34
> ### Describe your bug here.
> For some reason, I can't access the Mods menu! It just crashes with this error:

Send the file in a txt format

**Comment by NewbieTrustMe** [comment] 2023-03-12 20:24
i just released that a pack.json in one of the mods doesnt have a comma... i am so stupid

**Comment by TheKitBoi** [comment] 2023-03-12 20:41
close this issud

**Closed** 2023-03-14 21:29 UTC
Labels: bug
