### ISSUE TITLE
Game crashes when entering some songs.

### ISSUE THREAD

**Issue by KindaDumb** [ShadowMario/FNF-PsychEngine#10098] opened 2022-08-07 20:17 UTC
### Describe your bug here.

When I try to enter a song the game crashes, but only on certain ones and I'm not sure why.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2496)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment] 2022-08-07 20:25
Duplicate of several issues, look up the error

**Comment by Ninjakaiden523** [comment] 2022-08-08 03:16
It's a "Null object reference", make sure all the images and assets that are being called on exist. so if your character's .JSON has the .PNG file misnamed it will crash saying this, if you want to test this, download a psych mod (or the base engine) and go to "assets/characters" and open up bf.JSON go all the way down and remove one letter from "BOYFRIEND"

**Comment by KindaDumb** [comment] 2022-08-08 21:33
Figured it out, apparently there was a null event that was causing the game to crash. (Note that I didn't add any custom events)

**Closed** 2022-08-08 21:35 UTC
Labels: bug
