### ISSUE TITLE
Character Editor menu shows a black screen

### ISSUE THREAD

**Issue by DamianBossPL** [ShadowMario/FNF-PsychEngine#15273] opened 2024-08-08 19:00 UTC
### Describe your bug here.

On Linux, the Character Editor presents a black screen when loaded. This issue isn't present on Windows builds of the game.

Windows:
![image](https://github.com/user-attachments/assets/4851c19b-bbd8-4063-a1fb-b0f1097c9729)
Linux:
![image](https://github.com/user-attachments/assets/7925f036-7389-4722-95b6-4d6fc75644a1)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment] 2024-08-10 01:10
Duplicate of #15144

(The way to solve your issue is in the comments)

**Closed** 2024-08-16 17:52 UTC
Labels: bug
