### ISSUE TITLE
Character Editor animation error

### ISSUE THREAD

**Issue by brunobrunobr** [ShadowMario/FNF-PsychEngine#12495] opened 2023-05-29 21:36 UTC
### Describe your bug here.

alright so, there is this bug that keeps happening with me and idk how to fix, so when i add a animation that has a similar name to another ( like for example: "left" and then there is another which is named "left miss" or "left alt" the miss or alt animation overlaps with the left pose, turning the left pose into a miss, or another animation, idk if i have to be more specific with the names, like call it " character left pose " and then name the miss and alt "character left miss pose" or something, but it is very annoying, idk if this question has already been asked before, but it would be pretty cool to have it fixed.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried to add a character, but i don't think thats what your asking lol

**Comment by frantastic24** [comment] 2023-05-29 22:20
not a bug
duplicate of #2075

**Closed** 2023-07-19 18:08 UTC
Labels: bug
