### ISSUE TITLE
Are you able to have ending dialogue?

### ISSUE THREAD

**Issue by Gavman69** [ShadowMario/FNF-PsychEngine#692] opened 2021-10-29 20:27 UTC
### What is your question?

Are you able to have ending dialogue? and if so how? I want some ending dialogue for my mod but I have no idea how to do it. or if it even exists.

**Comment by ShadowMario** [comment] 2021-10-30 04:51
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/303

**Closed by ShadowMario** 2021-10-30 04:51 UTC
Labels: question
