### ISSUE TITLE
Vocals replaying in a song.

### ISSUE THREAD

**Issue by EpicShapeShifter** [ShadowMario/FNF-PsychEngine#10317] opened 2022-08-26 17:25 UTC
### Describe your bug here.

In certain songs where the vocals end before Inst, the vocals will start to replay before the song ends. I've seen this happen in blammed and thorns.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Lots of stuff. But nothing to do with vocals

**Comment by frantastic24** [comment] 2022-08-26 17:38
Not a psych issue + duplicate of #6551

**Comment by EpicShapeShifter** [comment] 2022-08-26 18:32
Well how do I fix vocal length then?

**Comment by frantastic24** [comment] 2022-08-26 18:34
It's explained in that old issue

**Comment by EpicShapeShifter** [comment] 2022-08-26 18:35
no it's not

**Comment by EpicShapeShifter** [comment] 2022-08-26 18:35
how do I extend vocal track length?

**Comment by frantastic24** [comment] 2022-08-26 18:35
Use any audio editing software

**Comment by Parsellol** [comment] 2022-09-29 12:07
close the issue

**Closed** 2022-11-12 12:47 UTC
Labels: bug
