### ISSUE TITLE
Chart editor crashes when i try to reload the json 

### ISSUE THREAD

**Issue by AudieAnimates** [ShadowMario/FNF-PsychEngine#11196] opened 2022-11-10 02:41 UTC
### Describe your bug here.

so im really confused on what to do, i have the json file for the chart in the correct spot but every time i press reload json it just crashes. reloading the audio is fine and also reloading from my autosave works too

ive tried asking on different discord servers and even twitter but the only response i got was "might be a source code issue" but i have no clue how to fix it

![why](https://user-images.githubusercontent.com/111212652/200986591-ae1dfc2d-8a4b-4d9f-8bcd-c7c3b92aa659.png)
![uhh](https://user-images.githubusercontent.com/111212652/200986767-222d9e4e-443f-4dcc-a71d-7e0e296cb7ad.JPG)

i think im modding it from source? i got the build from github and compiled it but apologies if i do mislabel it as this is my first time making a mod

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-11-10 03:16
Not a bug
It's not in the right spot, you create another folder with the song name, then the charts go inside

**Comment by AudieAnimates** [comment] 2022-11-10 03:37
> Not a bug It's not in the right spot, you create another folder with the song name, then the charts go inside

omg thank you lol, i was under the impression that i was supposed to just slap the charts in the folder and nothing else

**Comment by frantastic24** [comment] 2022-11-10 03:55
You can close the issue

**Closed** 2023-07-19 17:54 UTC
Labels: bug
