### ISSUE TITLE
Smaller pixel notes/strums

### ISSUE THREAD

**Issue by XtraXD1** [ShadowMario/FNF-PsychEngine#1258] opened 2021-11-22 14:43 UTC
### Describe your bug here.

The pixel notes and strums are smaller than normally. Here's a screenshot of i
!t:
[Captura.png](https://user-images.githubusercontent.com/78706741/142880951-3638861e-a007-498d-ad68-95be2e08ba6d.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the most recent build today, approximately at 01:00 (Timezone in Argentina) and builded it.

**Comment by 4ka1** [comment] 2021-11-22 15:17
Just modify these things in Note.hx and StrumNote.hx and it should be solved.

![](https://user-images.githubusercontent.com/92552094/142886538-ca02ca50-d4fe-4d07-8939-50070544205b.png)
![](https://user-images.githubusercontent.com/92552094/142886670-58c247ec-c780-4c83-ac28-0d5aa5f00851.png)

**Comment by ShadowMario** [comment] 2021-11-22 17:31
Duplicate of #1037 
Fixed yesterday.

**Closed by ShadowMario** 2021-11-22 17:31 UTC
Labels: bug
