### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by ZonicSpeeds** [ShadowMario/FNF-PsychEngine#12597] opened 2023-06-21 15:48 UTC
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/110855324/7b54ecf4-4c66-4db2-8551-7c944404e41e)
This pops up every time I try to load my custom stage.

Here is the code I put in the custom stage.
function onCreate()
	-- background shit
	
	close(true);
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I have not.

**Comment by frantastic24** [comment] 2023-06-21 15:58
Not a bug
Duplicate of #12124

**Comment by DanielHampel2010** [comment] 2023-07-14 12:34
When i was about to play my chart, and then this happened.

**Closed** 2023-07-19 18:26 UTC
Labels: bug
