### ISSUE TITLE
chart speed (issue resolved)

### ISSUE THREAD

**Issue by NastyIsDumb** [ShadowMario/FNF-PsychEngine#11594] opened 2022-12-27 23:25 UTC
### Describe your bug here.

in the last psych engine build the note speed dosn't change when you put it on the debug mode

example

if you put 2.6 speed in gameplay will be in 1 speed
and that with all numbers

that happens in .lua weeks and the story mode weeks basically in all the game

thx if this bug get fixed soon

-nasty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah in moddin normal stuff , but i re installed and it happens everytime

**Comment by frantastic24** [comment] 2022-12-27 23:35
Not a bug and duplicate of several issues
Press Control in Freeplay/story, change scroll type

**Comment by NastyIsDumb** [comment] 2022-12-28 01:47
> Not a bug and duplicate of several issues Press Control in Freeplay/story, change scroll type

thx bro i thought it was a bug, i put the scroll in multiplicative and it work lol

**Comment by NastyIsDumb** [comment] 2022-12-28 01:51
sorry lol

**Closed** 2022-12-28 01:51 UTC
Labels: bug
