### ISSUE TITLE
timebar color thing

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#11242] opened 2022-11-15 22:46 UTC
### What is your question?

can you make it to where the timebar 's color is the dads healthbar color?
MAKE SURE ITS FOR "mods/scripts" or "mods/modpack/scripts"

**Comment by frantastic24** [comment] 2022-11-15 23:16
Duplicate of #9907

**Closed** 2023-07-19 18:19 UTC
Labels: question
