### ISSUE TITLE
Null Object Reference when loading custom stage

### ISSUE THREAD

**Issue by Tiguexel** [ShadowMario/FNF-PsychEngine#10254] opened 2022-08-20 18:56 UTC
### Describe your bug here.

i made a custom stage that are just 2 images (the background and the ground) and if i try to load them in any song the game just crashes

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 451)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this bug to the GitHub: https://github.com/ShadowMario/FNF-PsychEngine

>Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-08-20 19:03
not a bug
stage json is missing character positions

**Comment by Tiguexel** [comment] 2022-08-20 19:17
oh thanks

**Comment by frantastic24** [comment] 2022-08-20 19:38
You can close the issue

**Comment by TheKitBoi** [comment] 2022-08-20 22:13
Close the issue
![Uploading 656E91BF-512F-42EB-9E9F-D25AB00603E3.jpeg…]()

**Comment by TheKitBoi** [comment] 2022-08-20 22:13
Close the issue
![13E8E394-C765-4E88-A347-38CD03DDE990](https://user-images.githubusercontent.com/84044666/185767785-caeb3226-82cb-487c-835e-28ba38ccb84c.jpeg)

**Closed** 2022-10-09 16:53 UTC
Labels: bug
