### ISSUE TITLE
Error with loading mods.

### ISSUE THREAD

**Issue by LemonoidInvasion** [ShadowMario/FNF-PsychEngine#11867] opened 2023-02-06 16:40 UTC
### Describe your bug here.

Hello. For some reason, when I load a mod and go into the menus (story, freeplay, awards etc.) it crashes

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 147)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
FreeplayState.hx (line 60)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 0 at position 0
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, I just added a mod.

**Comment by frantastic24** [comment] 2023-02-06 16:47
Not a bug
You have a broken week json

**Comment by LemonoidInvasion** [comment] 2023-02-06 16:52
oh

**Comment by LemonoidInvasion** [comment] 2023-02-06 16:54
i just checked, the week jsons are empty.
(btw its a challeng-edd mod)

**Comment by TheKitBoi** [comment] 2023-02-06 17:01
send the file (rename it to .txt)

**Comment by LemonoidInvasion** [comment] 2023-02-06 17:37
i fixed it dont worry

**Comment by CaptainBaldi** [comment] 2023-02-06 17:55
close the issue

**Comment by LemonoidInvasion** [comment] 2023-02-07 15:17
how do i do that

**Comment by LemonoidInvasion** [comment] 2023-02-07 15:17
okay i found out

**Closed** 2023-02-07 15:17 UTC
Labels: bug
