### ISSUE TITLE
debug menu error

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#11497] opened 2022-12-15 13:27 UTC
### Describe your problem here.

when i press 7 during song this error appearce
![image](https://user-images.githubusercontent.com/119149152/207870728-c875d8df-269b-42e4-8a7c-904f850e343a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added new characters, images, notetypes, mechanics etc

**Comment by Ratio-Combinder** [comment] 2022-12-15 14:44
not a bug
your dad health icon is broken

**Comment by vesel4ak** [comment] 2022-12-16 07:18
> not a bug your dad health icon is broken

oh now i know whats my problem, tysm

**Comment by Ratio-Combinder** [comment] 2022-12-16 09:17
![close the issue anim](https://user-images.githubusercontent.com/120575989/208064996-9c041984-89ed-4ef0-bda2-0054e0b6d971.gif)

close this issue

**Closed** 2022-12-31 08:48 UTC
Labels: help wanted
