### ISSUE TITLE
How do I make the arrow's hitbox smaller?

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#14112] opened 2024-02-06 09:27 UTC
### Describe your problem here.

I'm making an instakill note, but I get killed when pressing REALLY early

https://github.com/ShadowMario/FNF-PsychEngine/assets/95385133/af884c41-f7e0-4ff8-98f8-7469117cee69

```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'instakill' then
			setPropertyFromGroup('unspawnNotes', i, 'rgbShader.r', 0x000000);
			setPropertyFromGroup('unspawnNotes', i, 'rgbShader.g', 0xFF0000); --Change color
			setPropertyFromGroup('unspawnNotes', i, 'rgbShader.b', 0x330000);
			
			setPropertyFromGroup('unspawnNotes', i, 'lowPriority', true);
			
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'instakill' then
		setProperty('health', -500);
	end
end
```

How can I shrink the hitbox of my instakill arrow?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment] 2024-02-06 21:44
Duplicate of #13418

**Closed** 2024-05-06 21:56 UTC
Labels: help wanted
