### ISSUE TITLE
Speed rates

### ISSUE THREAD

**Issue by dum-du-m** [ShadowMario/FNF-PsychEngine#1225] opened 2021-11-21 16:35 UTC
### What feature do you want to get added on the base engine?

I would like changeable speed on songs to be added to Psych Engine.

**Comment by NS-Unfair** [comment] 2021-11-21 19:52
@dum-du-m, this is already a feature. In Lua, you can use setProperty('SONG.speed',speed) to set the scroll speed.

**Comment by ShadowMario** [comment] 2021-11-22 00:06
Duplicate of #317

**Closed by ShadowMario** 2021-11-22 00:06 UTC
Labels: enhancement

**Comment by dum-du-m** [comment] 2021-11-22 08:35
> @dum-du-m, this is already a feature. In Lua, you can use setProperty('SONG.speed',speed) to set the scroll speed.



> Duplicate of #317

not what i meant, like this https://youtu.be/HooSd3Z2ltE
