### ISSUE TITLE
I tried loading my new character and

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#10193] opened 2022-08-14 14:16 UTC
### Describe your bug here.

This popped up.
![image](https://user-images.githubusercontent.com/106406304/184541087-b18f78ca-e344-42a0-903c-518aa015edd7.png)
What happened?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-08-14 14:21
Not a bug
JSON file is broken

**Comment by imalink100** [comment] 2022-08-14 17:02
> Not a bug JSON file is broken

i dont trust you anymore so no

**Comment by frantastic24** [comment] 2022-08-14 17:11
Okay edgy

**Comment by imalink100** [comment] 2022-08-14 17:14
> Okay edgy

If anything is broken, it's your brain.

**Comment by frantastic24** [comment] 2022-08-14 17:16
Okay edgy

**Comment by CrusherNotDrip** [comment] 2022-08-14 19:33
broken json file

**Comment by PsychEnjoyer** [comment] 2022-08-15 15:09
It looks like its an actual fault with the json file. cause if you look at the top it mentions something about jsons.

**Comment by frantastic24** [comment] 2022-08-22 06:49
Close this and fix your shit

**Comment by imalink100** [comment] 2022-08-26 23:55
> broken json file

NO

**Comment by imalink100** [comment] 2022-08-26 23:56
> It looks like its an actual fault with the json file. cause if you look at the top it mentions something about jsons.

no.

**Comment by imalink100** [comment] 2022-08-26 23:56
> Close this and fix your shit

N O

**Comment by frantastic24** [comment] 2022-08-27 00:07
Why ask for help then act like a bitch lol just close this you clown

**Comment by imalink100** [comment] 2022-08-27 00:44
> Why ask for help then act like a bitch lol just close this you clown

the json file has errors when i make it. i cannot contol.

**Comment by frantastic24** [comment] 2022-08-27 01:19
Are you ever going to post the file or no

**Comment by imalink100** [comment] 2022-08-27 02:37
> Are you ever going to post the file or no

I'll try if i can

**Comment by imalink100** [comment] 2022-08-27 02:38
I can't
![image](https://user-images.githubusercontent.com/106406304/187011081-ba5f3114-8992-4747-aa61-27c8a3de4afc.png)

**Comment by TheKitBoi** [comment] 2022-08-27 02:40
Change json to txt

**Comment by imalink100** [comment] 2022-08-27 02:53
> Change json to txt

![image](https://user-images.githubusercontent.com/106406304/187011570-2ef55397-c665-4b0e-b472-e410b21afac0.png)

**Comment by TheKitBoi** [comment] 2022-08-27 03:12
copy and paste the text from the json and paste it here

**Comment by imalink100** [comment] 2022-08-27 17:36
{
	"animations": [
		{
			"offsets": [
				-5,
				0
			],
			"loop": false,
			"fps": 24,
			"anim": "idle",
			"indices": [],
			"name": "IDLE"
		},
		{
			"offsets": [
				5,
				-6
			],
			"loop": false,
			"fps": 24,
			"anim": "singLEFT",
			"indices": [],
			"name": "LEFT0"
		},
		{
			"offsets": [
				-20,
				-51
			],
			"loop": false,
			"fps": 24,
			"anim": "singDOWN",
			"indices": [],
			"name": "DOWN0"
		},
		{
			"offsets": [
				-46,
				27
			],
			"loop": false,
			"fps": 24,
			"anim": "singUP",
			"indices": [],
			"name": "UP0"
		},
		{
			"offsets": [
				-48,
				-7
			],
			"loop": false,
			"fps": 24,
			"anim": "singRIGHT",
			"indices": [],
			"name": "RIGHT0"
		},
		}
	],
	"no_antialiasing": false,
	"image": "characters/og_dave",
	"position": [
		0,
		350
	],
	"healthicon": "bf",
	"flip_x": true,
	"healthbar_colors": [
		49,
		176,
		209
	],
	"camera_position": [
		0,
		0
	],
	"sing_duration": 4,
	"scale": 1
}

**Comment by frantastic24** [comment] 2022-08-27 17:51
there's the problem, there an extra bracket and comma for some reason
![image](https://user-images.githubusercontent.com/95725102/187042117-733809a4-c38b-43d6-9c30-60bd3e1f4d93.png)

**Comment by imalink100** [comment] 2022-08-27 17:59
> there's the problem, there an extra bracket and comma for some reason ![image](https://user-images.githubusercontent.com/95725102/187042117-733809a4-c38b-43d6-9c30-60bd3e1f4d93.png)

ah.

**Closed** 2022-08-27 18:01 UTC
Labels: bug
