### ISSUE TITLE
"source/StoryMenuState.hx:323: characters 12-14 : Expected )"

### ISSUE THREAD

**Issue by Tommy3897** [ShadowMario/FNF-PsychEngine#2212] opened 2021-12-16 03:40 UTC
### Describe your problem here.

Whenever I run the lime test command it would always show me this message "source/StoryMenuState.hx:323: characters 12-14 : Expected )" Help?

The code is:
if(image is FlxGraphic)
![image](https://user-images.githubusercontent.com/82678900/146304068-4f6538e3-bcb2-440c-806c-194cb8c81a64.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FuseIsHere813** [comment] 2021-12-16 03:47
duplicate of #2053, #2049, #2038, #2028, #2027, #2026, #2024 #2067 #2074 #2167

_**update your haxe, stop using 4.1.5.**_

**Closed** 2021-12-16 03:51 UTC
Labels: help wanted

**Comment by VRfunkin** [comment] 2021-12-18 04:26
It probly the update of haxe time now i guess im right????
