### ISSUE TITLE
Charting fails to line up with newly added Time Signatures

### ISSUE THREAD

**Issue by Bloopsdoob** [ShadowMario/FNF-PsychEngine#10047] opened 2022-08-04 11:25 UTC
### Describe your bug here.

When using any measure length outside of 4, note placement will fail to line up with the cursor's placement on the grid. 

This is easily done, and a video attached displays this bug.

https://user-images.githubusercontent.com/77730957/182835284-2318edac-5e88-4253-9de3-0c3f6f6a1d47.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A, vanilla psych (0.6.2)

**Comment by tylerandari12** [comment] 2022-08-04 11:33
I couldn't find the original post but this is a duplicate of an earlier issue...

But this is a bug lol...

**Comment by ShadowMario** [comment] 2022-08-08 23:42
Not a bug, just didn't bothered making it change the notes position since it wouldn't match the song anyway.

**Closed by ShadowMario** 2022-08-08 23:42 UTC
Labels: bug
