### ISSUE TITLE
i cant import characters

### ISSUE THREAD

**Issue by aariztheapple** [ShadowMario/FNF-PsychEngine#11399] opened 2022-12-04 09:19 UTC
### Describe your bug here.

pressing reload image crashes the game along with the message below

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 250)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none. i just added character.

**Comment by Cap6ailB3an** [comment] 2022-12-04 13:24
im not that good with programming, but maybe the name was diffrent then the orignal? (i dont know)

**Comment by frantastic24** [comment] 2022-12-04 16:15
Duplicate of #9296

**Comment by aariztheapple** [comment] 2023-01-29 04:21
> im not that good with programming, but maybe the name was diffrent then the orignal? (i dont know)

they're the same

**Comment by TheKitBoi** [comment] 2023-01-29 10:56
> > im not that good with programming, but maybe the name was diffrent then the orignal? (i dont know)
> 
> they're the same

send the xml

**Closed** 2023-07-19 17:56 UTC
Labels: bug
