### ISSUE TITLE
Can't add noteskin

### ISSUE THREAD

**Issue by BoltDT** [ShadowMario/FNF-PsychEngine#11144] opened 2022-11-05 23:22 UTC
### Describe your problem here.

I am trying to add in a custom noteskin, but despite following the directions to a tee, I can't get it to load in-game. I am working on 0.5.2, bc that's the only version that will let me edit characters, so if you know a fix, please hit me up 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Added 1 .png file and 1 .xml file

**Comment by frantastic24** [comment] 2022-11-06 00:05
Hard to tell without any of the files or an actual description of what's happening

**Comment by BoltDT** [comment] 2022-11-06 00:08
When I type the name of the skin in and add the notes, the notes are invisible. If I try to go in-game, an error message pops up.

**Comment by frantastic24** [comment] 2022-11-06 00:16
That's still barely any info
The point of the error is to post it, it's useless to just mention it

**Comment by BoltDT** [comment] 2022-11-06 00:18
Here's the text file for the error
[crash_2022-11-05_17'58'50.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9944929/crash_2022-11-05_17.58.50.txt)

**Comment by frantastic24** [comment] 2022-11-06 00:33
seems like a duplicate of #9507

**Closed** 2022-11-06 01:21 UTC
Labels: help wanted
