### ISSUE TITLE
Error with trying to change character

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#10964] opened 2022-10-23 02:48 UTC
### Describe your bug here.

I'm trying to make a virgin rage cover playable (https://www.youtube.com/watch?v=GXA1pjBW3Xs&t=85s) and whenever i try to switch to sonic.exe, an error appears. 

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2868)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-10-23 03:09
Duplicate of #9539

**Closed** 2023-07-19 17:31 UTC
Labels: bug
