### ISSUE TITLE
WHAT IS THIS

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#10585] opened 2022-09-18 21:31 UTC
### Describe your bug here.

WHAT IS THIS
![image](https://user-images.githubusercontent.com/106406304/190928807-63f9d2de-1d27-400d-b8e5-78221b4fcd7e.png)

### Command Prompt/Terminal logs (if existing)

```bash
tfhfgh5ethbdetghegbtd
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by cinnadust** [comment] 2022-09-18 22:12
My research:
PlayState - if (trainMoving)
FlxState - couldn't find the file
FlxGame - couldn't find the file
EventDispatcher - couldn't find the file
DisplayObject - couldn't find the file

The conclusion I came to:
Some of the Philly train files might be deleted, try changing the stage

**Comment by frantastic24** [comment] 2022-09-18 22:20
duplicate of #9539

**Comment by imalink100** [comment] 2022-09-19 00:00
> My research: PlayState - if (trainMoving) FlxState - couldn't find the file FlxGame - couldn't find the file EventDispatcher - couldn't find the file DisplayObject - couldn't find the file
> 
> The conclusion I came to: Some of the Philly train files might be deleted, try changing the stage

prob not, i was trying to make a minus version of an existing psych engine mod

**Closed** 2023-07-19 17:23 UTC
Labels: bug
