### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KlaskyCsupo** [ShadowMario/FNF-PsychEngine#11992] opened 2023-02-27 19:27 UTC
### Describe your bug here.

PlayState.hx (line 2641)
PlayState.hx (line 2469)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by MemeHovy** [comment] 2023-02-27 19:29
missing note texture

**Comment by frantastic24** [comment] 2023-02-27 19:42
Not a bug and duplicate of several other issues
Philly Glow is hardcoded to week 3 stage

**Closed** 2023-07-19 18:03 UTC
Labels: bug
