### ISSUE TITLE
Array access is not allowed on (+ length : Int)

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#2234] opened 2021-12-16 19:47 UTC
### Describe your bug here.

weird bug with song.hx. its a completely clean copy of it from the source code with no modifications whatsoever.
![image](https://user-images.githubusercontent.com/79160331/146438413-9dcd1ddd-43ae-43c8-9d97-6383eef694d1.png)
![image](https://user-images.githubusercontent.com/79160331/146438419-d37296fe-3bce-422b-a143-fedc67faad24.png)

update: fixed typo

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not in song.hx no

**Comment by tposejank** [comment] 2021-12-16 20:06
duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 #2169 **update your haxe**.

**Comment by tposejank** [comment] 2021-12-16 20:07
@ShadowMario close

**Comment by DaBanana64** [comment] 2021-12-16 22:04
UPDATED YOUR [HAXE](https://haxe.org/download/)
DSFNSPFNR43-0T4U35

**Comment by loogchin** [comment] 2021-12-17 01:46
delete it

**Comment by 4wdthinks** [comment] 2021-12-17 16:39
> duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 #2169 **update your haxe**.

i updated my haxe and everything broke. thanks for that i guess?

**Comment by CrusherMods** [comment] 2021-12-17 19:09
> > duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 #2169 **update your haxe**.
> 
> i updated my haxe and everything broke. thanks for that i guess?

I updated my haxe and everything was fine

**Closed** 2021-12-20 02:59 UTC
Labels: bug

**Comment by DJAPK88** [comment] 2022-04-18 13:01
> > > duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 #2169 **update your haxe**.
> > 
> > 
> > i updated my haxe and everything broke. thanks for that i guess?
> 
> I updated my haxe and everything was fine

I updated everything and I get the same problem. What do I do?

**Comment by Wither362** [comment] 2022-05-17 17:07
> > > > duplicate of #2053 #2049 #2038 #2028 #2027 #2026 #2024 #2067 #2127 #2169 **update your haxe**.
> > > 
> > > 
> > > i updated my haxe and everything broke. thanks for that i guess?
> > 
> > 
> > I updated my haxe and everything was fine
> 
> I updated everything and I get the same problem. What do I do?

Reinstall the 4.2.4 version
