### ISSUE TITLE
Freeplay problem

### ISSUE THREAD

**Issue by Redlmpostor** [ShadowMario/FNF-PsychEngine#11315] opened 2022-11-25 22:31 UTC
### Describe your problem here.

when i enter the freeplay menu it says
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment] 2022-11-25 22:35
Duplicate of several issues
You messed up your week file

**Closed** 2023-07-19 15:56 UTC
Labels: help wanted
