### ISSUE TITLE
Compiling error with "LIME"

### ISSUE THREAD

**Issue by GordoiteYT** [ShadowMario/FNF-PsychEngine#10027] opened 2022-08-03 05:32 UTC
### Describe your bug here.

I followed this compiling tutorial for psych engine https://youtu.be/p2Q_K4gee0I
and I run "lime test windows" and it just shows up this error.
![bruh](https://user-images.githubusercontent.com/79427718/182531370-49531148-6a5f-4d5f-8af3-86692887a6e3.png)

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\"insert my user here"\Desktop\FNF source codings\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
'lime' is not recognized as an internal or external command,
operable program or batch file.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just followed the tutorial

**Comment by GordoiteYT** [comment] 2022-08-03 05:35
I moved it from it being in 2 folders to 1 and it still has the problem, I also moved it from the desktop and it still failed.

**Comment by frantastic24** [comment] 2022-08-03 05:51
Not a bug
You did not install lime

**Comment by tylerandari12** [comment] 2022-08-04 13:11
> Not a bug You did not install lime

That's weird...
I have Lime installed and it wont let me use it iether...

**Comment by frantastic24** [comment] 2022-08-04 14:23
Then it's not installed properly

**Comment by GordoiteYT** [comment] 2022-08-05 03:23
> > Not a bug You did not install lime
> 
> That's weird...
> I have Lime installed and it wont let me use it iether...

I realized what the problem is. After installing LIME, run "haxelib lime run setup" or what the documentation says about installing haxeflixel.

**Comment by tylerandari12** [comment] 2022-08-05 15:12
> > > Not a bug You did not install lime
> > 
> > 
> > That's weird...
> > I have Lime installed and it wont let me use it iether...
> 
> I realized what the problem is. After installing LIME, run "haxelib lime run setup" or what the documentation says about installing haxeflixel.

:O

**Comment by frantastic24** [comment] 2022-08-05 15:58
Close the issue

**Comment by GordoiteYT** [comment] 2022-08-19 18:32
> CLOSE THE DAMN ISSUE????

Alright chill. I'm on my phone right now.

**Comment by TheKitBoi** [comment] 2022-08-19 18:33
Then do it
![Uploading AC34CE80-BBB0-4DAA-AF7E-BC7E2A1C9EC4.jpeg…]()

**Comment by TheKitBoi** [comment] 2022-08-19 18:34
> Alright chill. I'm on my phone right now.
![511EF2CB-22A5-4574-A675-399FA22D2AEE](https://user-images.githubusercontent.com/84044666/185684674-49a7fb11-0b58-40cd-b870-b81cec470e25.jpeg)

**Closed** 2022-08-19 18:34 UTC
Labels: bug
