### ISSUE TITLE
Pack.json isnt working (0.7.1h)

### ISSUE THREAD

**Issue by chillultimated** [ShadowMario/FNF-PsychEngine#13226] opened 2023-09-01 02:54 UTC
### Describe your bug here.

Pack.json isnt working

Video of the Issue: https://youtu.be/L8fjr_1fVHU?si=_-KoYrvyf1IpXUJr

**I might be stupid but uhh idk what to do here**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment] 2023-09-01 03:52
Not a bug
You didn't escape the quotation mark, breaking the formatting
https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string

**Comment by chillultimated** [comment] 2023-09-01 05:04
> Not a bug You didn't escape the quotation mark, breaking the formatting https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string

I cant figure out wth is this and how to fix this-

**Comment by chillultimated** [comment] 2023-09-01 05:05
> > Not a bug You didn't escape the quotation mark, breaking the formatting https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string
> 
> I cant figure out wth is this and how to fix this-

ok, nvm, I did

**Comment by frantastic24** [comment] 2023-09-01 05:40
close the issue

**Closed** 2023-09-01 05:56 UTC
Labels: bug
