### ISSUE TITLE
A Null Object Reference bug as it seems

### ISSUE THREAD

**Issue by TheKing10002912** [ShadowMario/FNF-PsychEngine#10278] opened 2022-08-22 09:55 UTC
### Describe your bug here.

It happened after i saved a chart-hard.json and the events.json, before that everything was working properly, but now whenever i try loading the song, it starts, freezes, and crashes.
I can even open the chart editor if i'm quick enough, and there is nothing wrong with it, and i can't find anything missing in the stage files, unless that's the issue. But even then, i haven't changed the stage files at all, so they just stop working out of nowhere sound unlikely to me, but i don't know, if i did i wouldn't be here asking for help.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2868)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by CrusherNotDrip** [comment] 2022-08-22 14:51
If you put **Philly Glow** as an event its supposed to crash on purpose.

**Comment by TheKitBoi** [comment] 2022-08-22 15:08
> ### Describe your bug here.
> It happened after i saved a chart-hard.json and the events.json, before that everything was working properly, but now whenever i try loading the song, it starts, freezes, and crashes. I can even open the chart editor if i'm quick enough, and there is nothing wrong with it, and i can't find anything missing in the stage files, unless that's the issue. But even then, i haven't changed the stage files at all, so they just stop working out of nowhere sound unlikely to me, but i don't know, if i did i wouldn't be here asking for help.

then use this if you want to use it seprately
[Philly_Glow_Lua_Event.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9395472/Philly_Glow_Lua_Event.zip)
Credit CaptainKittyhawk

so close this issue
![close the dam issue](https://user-images.githubusercontent.com/84044666/185955203-2164e8c5-83a5-4e7c-a490-1c2db4a3e0f9.jpeg)

**Comment by frantastic24** [comment] 2022-08-22 15:29
Duplicate of #9539

**Closed** 2022-08-22 19:12 UTC
Labels: bug
