### ISSUE TITLE
How do I make a difficulty only available on Freeplay?

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#818] opened 2021-11-04 22:30 UTC
### What is your question?

.

**Comment by FuseIsHere813** [comment] 2021-11-04 23:22
Elaborate so we can know what your saying even more.

**Comment by WaFl-XIV** [comment] 2021-11-04 23:25
How do I disable a difficulty on Story Mode so the only way to access the difficulty is on Freeplay?

**Comment by ShadowMario** [comment] 2021-11-05 21:38
Duplicate of #645

**Closed by ShadowMario** 2021-11-05 21:38 UTC
Labels: question
