### ISSUE TITLE
Health gain on Hold Notes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9850] opened 2022-07-21 19:55 UTC
### What feature do you want to get added on the **base** engine?

I feel like, that maybe hold/sustain notes should be nerfed.
Like, if you keep on singing for a whole section, gives you WAY more health, than pressing all of the singular arrows in that section-

So, my suggestion is, that the hold notes maybe should then give like, half of the health, that single ones do?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment] 2022-07-23 02:15
Duplicate of  #9620

**Comment by TFLTV** [comment] 2022-07-23 15:27
**#ripKadeEngine**

**Comment by ManMaster707** [comment] 2022-07-23 18:56
> Duplicate of #9620

That's a pr? And why do you consider it a duplicate if he's asking a different thing than what you tried to implement?

(he isn't requesting to eliminate entriely the health gain on sustain notes, he's asking to lower it)

**Closed** 2022-08-01 23:59 UTC
Labels: enhancement
