### ISSUE TITLE
events change Background

### ISSUE THREAD

**Issue by xfoxstrot** [ShadowMario/FNF-PsychEngine#1937] opened 2021-12-11 12:40 UTC
### What is your question?

Hello. 

We have event  changeCharacters at FNF. 
Tell me please how to make events change background?

**Comment by CrusherMods** [comment] 2021-12-11 15:22
its not an event

**Comment by xfoxstrot** [comment] 2021-12-11 15:25
I mean, I want to change background during song, how do I make it?

**Comment by CrusherMods** [comment] 2021-12-11 15:29
> I mean, I want to change background during song, how do I make it?

oh Idk but there may be duplicates of this issue so you can go look for them someone may of gave the way

**Comment by PDL2CGamejolt** [comment] 2021-12-11 15:42
i wanna have the event

**Comment by xfoxstrot** [comment] 2021-12-11 16:03
> > I mean, I want to change background during song, how do I make it?
> 
> oh Idk but there may be duplicates of this issue so you can go look for them someone may of gave the way

I don't found something.

**Comment by xfoxstrot** [comment] 2021-12-11 16:03
> i wanna have the event

Sorry, I don't understand what do you mean

**Comment by ShadowMario** [comment] 2021-12-11 16:59
Duplicate of multiple issues.

**Closed by ShadowMario** 2021-12-11 16:59 UTC
Labels: question
