### ISSUE TITLE
Game gives error and crashes when trying to load up custom song.

### ISSUE THREAD

**Issue by splooood** [ShadowMario/FNF-PsychEngine#6545] opened 2022-03-08 22:33 UTC
### Describe your bug here.

So I just finished downloading the new Psych Engine version and porting over my mods folder as well, and I decided to load up one of my custom songs to update it. When I selected the mod directory and opened the chart editor and tried to load up the chart, the game just gives an error and crashes. The chart worked perfectly fine in 0.5.1.

By the way this is what the error looked like:
![bruh](https://user-images.githubusercontent.com/79657828/157337171-5ff836ec-625d-4300-8825-40fd82e51a0f.png)

Edit: So loading up the song in Freeplay/Story Mode works but going to the Mod editor menu doesn't.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I ported over my old mods folder from 0.5.1 to 0.5.2.

**Comment by frantastic24** [comment] 2022-03-08 22:36
Missing difficulty json, not a bug

**Comment by frantastic24** [comment] 2022-03-08 22:37
Check your chart files, one seems to be missing

**Comment by mayo78** [comment] 2022-03-08 22:46
> Check your chart files, one seems to be missing

thats not the issue, an update added reloading jsons with specific difficulties but it breaks if you haven't loaded in a song yet

**Comment by frantastic24** [comment] 2022-03-08 22:51
So technically that is the issue
It only "breaks" because it uses normal by default
But fair enough, it should look for a valid difficulty if normal isn't found to fix the oversight

**Comment by Theoyeah** [comment] 2022-03-09 15:10
normally fixed in 0.5.2

**Closed** 2022-04-10 20:04 UTC
Labels: bug
