### ISSUE TITLE
adding loading screen 

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#8098] opened 2022-04-12 14:26 UTC
### Describe your problem here.

i wanted to add the loading screen when loading songs but idk how to do it please help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Randomxdp** [comment] 2022-04-13 12:16
I think he means the loading screen when loading a song, not THAT loading screen that youre talking abt 

> simple but if this is too hard sorry but before i tell you do you want it to be random loading screens

**Comment by RedMik52** [comment] 2022-04-13 15:09
> I think he means the loading screen when loading a song, not THAT loading screen that youre talking abt
> 
> > simple but if this is too hard sorry but before i tell you do you want it to be random loading screens

yes i mean the song loading screen not the preloading screen

**Comment by machonessiebaby** [comment] 2022-04-13 21:15
o then cant help sorry

**Comment by ShadowMario** [comment] 2022-04-15 05:08
Duplicate of #1728

**Closed by ShadowMario** 2022-04-15 05:08 UTC
Labels: help wanted
