### ISSUE TITLE
i don't know what to title this

### ISSUE THREAD

**Issue by DaPogMan** [ShadowMario/FNF-PsychEngine#1160] opened 2021-11-19 03:31 UTC
### Describe your problem here.

well, i've trying to change characters recently but i type Dad as the opponent in the 1 for the opponent character to change, but it changes the player character instead, i tried it with gf and bf and it does the same, it change sonly to bf

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MayoALT** [comment] 2021-11-19 12:42
the first part is for which char you want to change, and the second part is what you want the character to change into

**Comment by ShadowMario** [comment] 2021-11-20 00:25
Duplicate of #312

**Closed by ShadowMario** 2021-11-20 00:25 UTC
Labels: help wanted

**Comment by DaPogMan** [comment] 2021-11-20 06:59
yeah i did that, without the d in mayus and not, but still it changes boyfriend, i put the character that i wanted it to turn into (value 2) the correct name of the character and the (value 1) as Dad and tried dad like with the mayus and not and still changed boyfriend

**Comment by DaPogMan** [comment] 2021-11-20 08:27
nvm got it since i clicked the # thing
