### ISSUE TITLE
I need help making pre-song cutscenes

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#1098] opened 2021-11-17 19:13 UTC
### Describe your problem here.

I don't know how to make pre-song cutscenes (not dialogues), can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

2 new characters, a new stage and deleted week 1-6 default json and png

### hi

**Comment by acap09** [comment] 2021-11-17 19:14
### help me #

**Comment by ShadowMario** [comment] 2021-11-17 22:57
MP4 cutscenes on animated in sprites?

**Comment by acap09** [comment] 2021-11-18 05:29
MP4, i have the MP4, i believe it is already 1280x720. Just the coding is my problem.

**Comment by acap09** [comment] 2021-11-19 16:23
hi

**Comment by craftersshaft** [comment] 2021-11-20 23:45
there's a video example here for bopeebo, could probably be reworked to fit your needs: https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by ShadowMario** [comment] 2021-11-22 00:25
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/748

**Closed by ShadowMario** 2021-11-22 00:25 UTC
Labels: help wanted

**Comment by FedorVaice** [comment] 2022-02-22 09:33
And animated in sprites?
