### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by davman808** [ShadowMario/FNF-PsychEngine#1180] opened 2021-11-19 21:15 UTC
### What feature do you want to get added on the base engine?

i, as a linux user, would be happy if i could build mods made with this engine to linux, or at least have a version of it that doesnt have the discord_rpc in it, since thats whats throwing errors and not letting me build to neko. thank you in advance! (this is a screenshot from windows cus i ran out of space in my linux partition)
![mfingerror](https://user-images.githubusercontent.com/73218063/142692503-847c10aa-249c-4790-8dd5-6170e3fb4a7f.png)

**Comment by ShadowMario** [comment] 2021-11-20 00:04
Duplicate of #219

**Closed by ShadowMario** 2021-11-20 00:04 UTC
Labels: enhancement
