### ISSUE TITLE
Song Error

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#9447] opened 2022-07-02 06:31 UTC
### Describe your bug here.

It crashes if I enter a specific song.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 110)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
Song.hx (line 140)
Song.hx (line 132)
PlayState.hx (line 2310)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 93 at position 23507
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything on source code but I added some mods on lua.

**Comment by frantastic24** [comment] 2022-07-02 06:39
Not a bug
Your chart is fucked

**Comment by MOON-on-GitHub** [comment] 2022-07-02 06:47
It works now

thank you

**Comment by frantastic24** [comment] 2022-07-02 07:14
Close the issue

**Comment by MOON-on-GitHub** [comment] 2022-07-02 14:28
Close #9447

**Closed** 2022-07-02 14:29 UTC
Labels: bug
