### ISSUE TITLE
song speed (scroll speed) won't work

### ISSUE THREAD

**Issue by howareyou23** [ShadowMario/FNF-PsychEngine#12470] opened 2023-05-24 19:43 UTC
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/134549782/29599aff-337b-453a-98e4-50d48e6042b7)

https://github.com/ShadowMario/FNF-PsychEngine/assets/134549782/204d961d-6e40-45f2-9cc2-25651ad90581

i tried changing the song speed on a song but it just stays at 1
this is an example video of what i mean

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

h

**Comment by frantastic24** [comment] 2023-05-24 20:03
Duplicate of #8084

**Closed** 2023-07-19 18:08 UTC
Labels: bug
