### ISSUE TITLE
Wtf does this mean at all?

### ISSUE THREAD

**Issue by ChargerDoinDaCode** [ShadowMario/FNF-PsychEngine#1574] opened 2021-12-01 20:54 UTC
### Describe your bug here.

Ok so im tryna build psych engine so i pull up command prompt and i type: cd (file location for psych engine) and then i put down Lime test windows and then this error pops up saying:

source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'

Can you tell me whats going on?

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I haven't.

**Comment by CrusherMods** [comment] 2021-12-01 20:58
look at my pull request in the github to fix the problem I found a solution

**Comment by HiroOfc** [comment] 2021-12-01 21:11
duplicate of #1524

**Comment by ChargerDoinDaCode** [comment] 2021-12-01 21:31
> duplicate of #1524

that didn't help either in fact made the error worse

**Comment by ChargerDoinDaCode** [comment] 2021-12-01 21:31
> look at my pull request in the github to fix the problem I found a solution

Didn't work it just bugged it out more

**Comment by HiroOfc** [comment] 2021-12-01 22:19
> > look at my pull request in the github to fix the problem I found a solution
> 
> Didn't work it just bugged it out more

#1430 then, a person has answered better about it

**Comment by DaBanana64** [comment] 2021-12-02 12:34
It got fixed in the latest commit. Try doing a git pull.

**Closed** 2021-12-02 13:19 UTC
Labels: bug
