### ISSUE TITLE
HELP! source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall on Windows Powershell.

### ISSUE THREAD

**Issue by giannydeez** [ShadowMario/FNF-PsychEngine#14910] opened 2024-06-16 16:17 UTC
### Describe your problem here.

Everytime i try to use "lime test windows" i get "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall." I am on windows powershell and i've installing SScript and using setup/setup-windows.bat and the issue hasnt stopped. HELP
![help me please mod](https://github.com/ShadowMario/FNF-PsychEngine/assets/172931204/29728c07-c1dd-4a1f-9f0a-dbeb0c3c94e9)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment] 2024-06-16 18:37
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/14852

**Closed by ShadowMario** 2024-06-16 18:37 UTC
Labels: help wanted
