### ISSUE TITLE
cutscenes on mac port

### ISSUE THREAD

**Issue by Yohjihappy** [ShadowMario/FNF-PsychEngine#13563] opened 2023-11-05 17:21 UTC
### What feature do you want to get added on the **base** engine?

plss just do it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CaptainBaldi** [comment] 2023-11-05 18:32
invalid + ask the `hxCodec` dev's not shadowmario

**Comment by JonnycatMeow** [comment] 2023-11-06 01:05
there already is with the latest hxcodec

**Comment by ShadowMario** [comment] 2023-12-05 16:50
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/13430

**Closed by ShadowMario** 2023-12-05 16:50 UTC
Labels: duplicate, enhancement
