### ISSUE TITLE
animated bgs

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#968] opened 2021-11-11 17:33 UTC
### What feature do you want to get added on the base engine?

hey i hope im not bothering but can you add animated bg editors? like so you can put in animated bgs?

**Comment by ShadowMario** [comment] 2021-11-11 20:57
Are you fucking kidding me
Duplicate of #480 #540 #788 #921

**Closed by ShadowMario** 2021-11-11 20:57 UTC
Labels: enhancement
