### ISSUE TITLE
Has anyone gotten this error before?

### ISSUE THREAD

**Issue by Squeegee-designee** [ShadowMario/FNF-PsychEngine#10399] opened 2022-09-01 23:37 UTC
### Describe your bug here.

Whenever I go to the freeplay it keeps on breaking and it's displaying this error message:
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

Does anyone know how to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No just using the mods folder

**Comment by frantastic24** [comment] 2022-09-02 00:00
Not a bug
Make a new week file

**Comment by Squeegee-designee** [comment] 2022-09-02 00:13
> Not a bug Make a new week file

Ok I will! Thanks!

**Comment by TheKitBoi** [comment] 2022-09-02 00:45
Close this issue
![0BC5F44D-38D2-463C-8F61-3A584123CA9D](https://user-images.githubusercontent.com/84044666/188035592-39ddefbc-bf3a-43d5-8d19-8888ed01479c.jpeg)

**Comment by CrusherNotDrip** [comment] 2022-09-02 00:56
> Close this issue ![0BC5F44D-38D2-463C-8F61-3A584123CA9D](https://user-images.githubusercontent.com/84044666/188035592-39ddefbc-bf3a-43d5-8d19-8888ed01479c.jpeg)

I updated this photo just incase they say "where?" but I don't that that will happen anyways

![image](https://user-images.githubusercontent.com/90648119/188036606-4fcd0bc3-6fd7-4de8-adeb-3843b46e4551.png)

**Closed** 2023-07-19 17:19 UTC
Labels: bug
