### ISSUE TITLE
Easier way to add an extra difficulty (without needing to mod source code)

### ISSUE THREAD

**Issue by daisukidaisy** [ShadowMario/FNF-PsychEngine#1179] opened 2021-11-19 19:13 UTC
### What feature do you want to get added on the base engine?

this could essentially be done by using freeplaySonglist.txt and putting stuff in there instead of just leaving it there completely blank and unused.

each song could be a line in the file and would look like this:
[song name]:[icon]:Easy,Normal,Hard(,others):[week ID]:[other stuff]

**Comment by ShadowMario** [comment] 2021-11-20 00:09
Duplicate of #405

**Closed by ShadowMario** 2021-11-20 00:09 UTC
Labels: enhancement
