### ISSUE TITLE
How do I make custom achievements? (No Source Code)

### ISSUE THREAD

**Issue by DevonSonic** [ShadowMario/FNF-PsychEngine#8248] opened 2022-04-20 23:24 UTC
### Describe your problem here.

I don't know how to make an achievement :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by antoSKRLOL** [comment] 2022-04-20 23:49
n o

**Comment by HiroMizuki** [comment] 2022-04-21 00:39
impossible with lua at the moment

**Comment by ShadowMario** [comment] 2022-04-21 21:31
Duplicate of #6511

**Closed by ShadowMario** 2022-04-21 21:31 UTC
Labels: help wanted
