### ISSUE TITLE
error when adding a custom character

### ISSUE THREAD

**Issue by PurpleProgrammer12** [ShadowMario/FNF-PsychEngine#10806] opened 2022-10-10 03:25 UTC
### Describe your bug here.

basically, when trying to load my character sprite sheet this happens: "flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference". How do I fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only thing I did was add my character sprite sheet and .xml file

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:27
bruh

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:28
why the title so weird?

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:28
> why the title so weird?

idk what to put :(

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:29
> why the title so weird?

title fixed

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:30
> > why the title so weird?
> 
> idk what to put :(

the hell?

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:30
> > why the title so weird?
> 
> title fixed

at least its readable now

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:31
> > > why the title so weird?
> > 
> > 
> > title fixed
> 
> at least its readable now

:/

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:31
> > > > why the title so weird?
> > > 
> > > 
> > > title fixed
> > 
> > 
> > at least its readable now
> can you help tho?

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:32
idk,ask someone else

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:33
this is literally why I made the issue

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:34
bruh

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:34
imagine

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:34
https://github.com/LilDrippyMyFnf/FNF-BitEnigne

**Comment by frantastic24** [comment] 2022-10-10 03:36
Not a bug
Missing texture files

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:37
> Not a bug Missing texture files

wait so how do I fix it?

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:37
be

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:37
> > Not a bug Missing texture files
> 
> wait so how do I fix it?

he just said it

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:37
> Not a bug Missing texture files

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:38
> > Not a bug Missing texture files



> > > Not a bug Missing texture files
> > 
> > 
> > wait so how do I fix it?
> 
> he just said it

bro I low IQ WHAT TEXTURE FILE IS MISSING?

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:39
i'm stupid

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:39
> i'm stupid

XP

**Comment by ImaginationSuperHero528** [comment] 2022-10-10 03:40
> > > Not a bug Missing texture files
> 
> 
> 
> > > > Not a bug Missing texture files
> > > 
> > > 
> > > wait so how do I fix it?
> > 
> > he just said it
> 
> bro I low IQ WHAT TEXTURE FILE IS MISSING?

You definitely have a low iq... the texture you set in the json bro.

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:40
huh?..

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:40
> > > > Not a bug Missing texture files
> > 
> > 
> > > > > Not a bug Missing texture files
> > > > 
> > > > 
> > > > wait so how do I fix it?
> > > 
> > > 
> > > he just said it
> > 
> > 
> > bro I low IQ WHAT TEXTURE FILE IS MISSING?
> 
> You definitely have a low iq... the texture you set in the json bro.

exactly

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:41
> huh?..

you don't get what json is

**Comment by MemeHoovy** [comment] 2022-10-10 03:42
> huh?..

man you are fucking dumb

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:43
> > huh?..
> 
> man you are fucking dumb

FR

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:43
> huh?..

if you don't understand JSON,why did you make this?

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:44
wait the xml or the json

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:44
wait there's 2967 lines in there

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:45
> wait the xml or the json

YOU STUPID ITS JSON

**Comment by MemeHoovy** [comment] 2022-10-10 03:46
oh my fucking god

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:46
![Screenshot (58)](https://user-images.githubusercontent.com/115441069/194796673-6569cb11-f66d-4207-a962-112c301e4148.png)

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:47
> ![Screenshot (58)](https://user-images.githubusercontent.com/115441069/194796673-6569cb11-f66d-4207-a962-112c301e4148.png)

TOLD YOU ITS JSON

**Comment by MemeHoovy** [comment] 2022-10-10 03:47
https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-enable-hidden-file-extensions-in-Windows.html

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:47
> oh my fucking god

?

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:51
i genuinely don't know what texture is missing

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:52
> i genuinely don't know what texture is missing

this jit

**Comment by MemeHoovy** [comment] 2022-10-10 03:55
if you can't understand what a json is then we can't help you

**Comment by PurpleProgrammer12** [comment] 2022-10-10 03:57
wait the "right" animation is named rigth is that the error

**Comment by LilDrippyMyFnf** [comment] 2022-10-10 03:59
> 

bruh

**Comment by MemeHoovy** [comment] 2022-10-10 04:00
(ㆆ_ㆆ)

**Comment by frantastic24** [comment] 2022-10-10 04:01
Psych engine doesn't support .json format for textures, you need .xml

**Comment by PurpleProgrammer12** [comment] 2022-10-10 04:02
oh fuck

**Comment by PurpleProgrammer12** [comment] 2022-10-10 04:02
well you just saved my ass

**Comment by frantastic24** [comment] 2022-10-10 04:04
You can close the issue now

**Closed** 2022-10-10 04:16 UTC
Labels: bug
