### ISSUE TITLE
32Bit Psych Version is NOT actually 32Bit

### ISSUE THREAD

**Issue by marbloxy** [ShadowMario/FNF-PsychEngine#10889] opened 2022-10-18 13:25 UTC
### What is your question?

So i got that big BIG screen saying that i should update Psych Engine, when i did so i installed the 32bit version (cause my ass use 32bit AND win7) and then i get a big pop up saying it is 64bit compatible only.

I don't even know how new psych engine update look like cause of it, so i am wondering if it'll be fixed

**Comment by EyeDaleHim** [comment] 2022-10-18 13:46
32-bit may become unsupported unofficially, but you might have an issue if you still use a 32-bit PC.

**Comment by EyeDaleHim** [comment] 2022-10-18 13:47
> 32-bit may become unsupported unofficially, but you might have an issue if you still use a 32-bit PC.

Either way. try compiling 32-bit yourself? Or maybe verify if you have a 32-bit build or not

**Comment by marbloxy** [comment] 2022-10-18 14:20
> > 32-bit may become unsupported unofficially, but you might have an issue if you still use a 32-bit PC.
> 
> Either way. try compiling 32-bit yourself? Or maybe verify if you have a 32-bit build or not

i wanted to try that, but as i stated earlier i have a win7 and i cant compile anything. so i guess i will use 0.6.2 for a while until i upgrade my computer

**Comment by ShadowMario** [comment] 2022-10-20 00:34
Literally a duplicate of the issue before yours, god damn it dude.

**Closed by ShadowMario** 2022-10-20 00:34 UTC
Labels: duplicate, question
