### ISSUE TITLE
Background to the left of characters

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#10876] opened 2022-10-16 19:35 UTC
### Describe your bug here.

![image](https://user-images.githubusercontent.com/106406304/196054446-b19ad553-51da-4b21-bffa-99503014639a.png)
it just doesn't put the stage in the right place and i don't know how to fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

tried adding a black square next to it to adjust the stage, didn't work

**Comment by frantastic24** [comment] 2022-10-16 19:41
Not a bug
What if, hear me out, you changed coordinates?!?!

**Comment by imalink100** [comment] 2022-10-16 19:45
> Not a bug What if, hear me out, you changed coordinates?!?!

coordinates of what

**Comment by frantastic24** [comment] 2022-10-16 19:46
Images, characters, literally anything?

**Comment by imalink100** [comment] 2022-10-16 19:48
> Images, characters, literally anything?

how are you supposed to change coordinates of a stage, there's no such thing as a "stage editor"

**Comment by Gostar64** [comment] 2022-10-16 19:53
> > Images, characters, literally anything?
> 
> how are you supposed to change coordinates of a stage, there's no such thing as a "stage editor"

the stage lua file to move the background or the stage json to move the characters

**Comment by frantastic24** [comment] 2022-10-16 20:06
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions
Close the issue and read the wiki

**Comment by CaptainBaldi** [comment] 2022-10-16 20:32
> > Images, characters, literally anything?
> 
> how are you supposed to change coordinates of a stage, there's no such thing as a "stage editor"

how the fuck do you know how to make a lua sprite and stage files but you somehow don't know how to change positions of the sprites

**Closed** 2023-07-19 17:26 UTC
Labels: bug
