### ISSUE TITLE
Change Character to "dad" not working

### ISSUE THREAD

**Issue by LeGoldenBoots** [ShadowMario/FNF-PsychEngine#735] opened 2021-10-31 18:15 UTC
### Describe your bug here.

Whenever i try to change the opponent to another character using the "Change Character" event, It replaces BF instead of Dad. How do I fix this?

### Are you modding a build from source or with Lua?

- [ ] Lua
- [x] Source

### What is your build target?

- [X] Windows
- [ ] Linux
- [ ] Mac
- [ ] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit or change anything in the source code.

**Comment by bodyakod** [comment] 2021-10-31 18:20
I have the same рroblem, I wish they fix this ASAР.

**Comment by titopops** [comment] 2021-10-31 19:29
If I'm correct, for the "Change Character" event, leaving the value blank switches BF, 1 switches Dad, and 2 switches the GF, another thing to note that if the character doesn't exist, its set to bf by default

**Comment by ShadowMario** [comment] 2021-11-01 17:27
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/591

**Closed by ShadowMario** 2021-11-01 17:27 UTC
Labels: bug
