### ISSUE TITLE
Scripts Problem

### ISSUE THREAD

**Issue by TheHalfBunnyLXKD** [ShadowMario/FNF-PsychEngine#2876] opened 2021-12-30 01:25 UTC
### Describe your bug here.

i've deleted a script from the mods folder, but the script is still being loaded

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited alot of stuff.

**Comment by tposejank** [comment] 2021-12-30 01:43
restart the game

**Comment by ShadowMario** [comment] 2021-12-30 14:52
You probably have a duplicate of the lua script somewhere.

**Closed by ShadowMario** 2021-12-30 14:52 UTC
Labels: bug
